go_library(
    name = "file",
    srcs = ["file.go"],
    visibility = [
        "//chat",
        "//chat/store",
        "//diff",
        "//embed",
        "//internal/configuration",
    ],
    deps = [
        "//third_party/go:github.com__pkg__errors",
        "//third_party/go:github.com__spf13__cobra",
    ],
)
