// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: sgpt/v1/configuration.proto

//go:build protoopaque

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/malonaz/core/genproto/ai/ai_engine/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Configuration for the sgpt tool.
type Configuration struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_GrpcClients *[]*GrpcClient         `protobuf:"bytes,1,rep,name=grpc_clients,json=grpcClients,proto3"`
	xxx_hidden_AiService   string                 `protobuf:"bytes,2,opt,name=ai_service,json=aiService,proto3"`
	xxx_hidden_Models      *[]*Model              `protobuf:"bytes,3,rep,name=models,proto3"`
	xxx_hidden_Chat        *ChatConfiguration     `protobuf:"bytes,4,opt,name=chat,proto3"`
	xxx_hidden_Ignore      []string               `protobuf:"bytes,6,rep,name=ignore,proto3"`
	xxx_hidden_Title       string                 `protobuf:"bytes,7,opt,name=title,proto3"`
	xxx_hidden_Imports     *[]*Import             `protobuf:"bytes,8,rep,name=imports,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Configuration) Reset() {
	*x = Configuration{}
	mi := &file_sgpt_v1_configuration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration) ProtoMessage() {}

func (x *Configuration) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_configuration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Configuration) GetGrpcClients() []*GrpcClient {
	if x != nil {
		if x.xxx_hidden_GrpcClients != nil {
			return *x.xxx_hidden_GrpcClients
		}
	}
	return nil
}

func (x *Configuration) GetAiService() string {
	if x != nil {
		return x.xxx_hidden_AiService
	}
	return ""
}

func (x *Configuration) GetModels() []*Model {
	if x != nil {
		if x.xxx_hidden_Models != nil {
			return *x.xxx_hidden_Models
		}
	}
	return nil
}

func (x *Configuration) GetChat() *ChatConfiguration {
	if x != nil {
		return x.xxx_hidden_Chat
	}
	return nil
}

func (x *Configuration) GetIgnore() []string {
	if x != nil {
		return x.xxx_hidden_Ignore
	}
	return nil
}

func (x *Configuration) GetTitle() string {
	if x != nil {
		return x.xxx_hidden_Title
	}
	return ""
}

func (x *Configuration) GetImports() []*Import {
	if x != nil {
		if x.xxx_hidden_Imports != nil {
			return *x.xxx_hidden_Imports
		}
	}
	return nil
}

func (x *Configuration) SetGrpcClients(v []*GrpcClient) {
	x.xxx_hidden_GrpcClients = &v
}

func (x *Configuration) SetAiService(v string) {
	x.xxx_hidden_AiService = v
}

func (x *Configuration) SetModels(v []*Model) {
	x.xxx_hidden_Models = &v
}

func (x *Configuration) SetChat(v *ChatConfiguration) {
	x.xxx_hidden_Chat = v
}

func (x *Configuration) SetIgnore(v []string) {
	x.xxx_hidden_Ignore = v
}

func (x *Configuration) SetTitle(v string) {
	x.xxx_hidden_Title = v
}

func (x *Configuration) SetImports(v []*Import) {
	x.xxx_hidden_Imports = &v
}

func (x *Configuration) HasChat() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Chat != nil
}

func (x *Configuration) ClearChat() {
	x.xxx_hidden_Chat = nil
}

type Configuration_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Named gRPC clients, referenced elsewhere by name.
	GrpcClients []*GrpcClient
	// Name of the gRPC client to use for the AI service.
	AiService string
	// Model aliases.
	Models []*Model
	// Chat configuration.
	Chat *ChatConfiguration
	// Ignore patterns (gitignore syntax) applied on top of .gitignore files
	// whenever sgpt walks directory trees (graph scans, file discovery).
	Ignore []string
	// Human-readable title: a few lines about the repo this configuration
	// (or configuration override) belongs to.
	Title string
	// External repos whose roles and tool sets are addressable as
	// "@{name}@{selector}" (e.g. "@github.com/malonaz/core@go/grpc:architecture"
	// or --role "@github.com/malonaz/core@reviewer").
	Imports []*Import
}

func (b0 Configuration_builder) Build() *Configuration {
	m0 := &Configuration{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_GrpcClients = &b.GrpcClients
	x.xxx_hidden_AiService = b.AiService
	x.xxx_hidden_Models = &b.Models
	x.xxx_hidden_Chat = b.Chat
	x.xxx_hidden_Ignore = b.Ignore
	x.xxx_hidden_Title = b.Title
	x.xxx_hidden_Imports = &b.Imports
	return m0
}

// An external repo, imported by local path.
type Import struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Path string                 `protobuf:"bytes,2,opt,name=path,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Import) Reset() {
	*x = Import{}
	mi := &file_sgpt_v1_configuration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Import) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Import) ProtoMessage() {}

func (x *Import) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_configuration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Import) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Import) GetPath() string {
	if x != nil {
		return x.xxx_hidden_Path
	}
	return ""
}

func (x *Import) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Import) SetPath(v string) {
	x.xxx_hidden_Path = v
}

type Import_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Name of the import (e.g. "github.com/malonaz/core").
	Name string
	// Absolute path (or ~-prefixed) of the repo's root directory.
	Path string
}

func (b0 Import_builder) Build() *Import {
	m0 := &Import{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Path = b.Path
	return m0
}

// gRPC client configuration.
type GrpcClient struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name         string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_BaseUrl      string                 `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3"`
	xxx_hidden_ApiKey       string                 `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3"`
	xxx_hidden_ApiKeyHeader string                 `protobuf:"bytes,4,opt,name=api_key_header,json=apiKeyHeader,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GrpcClient) Reset() {
	*x = GrpcClient{}
	mi := &file_sgpt_v1_configuration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcClient) ProtoMessage() {}

func (x *GrpcClient) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_configuration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GrpcClient) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *GrpcClient) GetBaseUrl() string {
	if x != nil {
		return x.xxx_hidden_BaseUrl
	}
	return ""
}

func (x *GrpcClient) GetApiKey() string {
	if x != nil {
		return x.xxx_hidden_ApiKey
	}
	return ""
}

func (x *GrpcClient) GetApiKeyHeader() string {
	if x != nil {
		return x.xxx_hidden_ApiKeyHeader
	}
	return ""
}

func (x *GrpcClient) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *GrpcClient) SetBaseUrl(v string) {
	x.xxx_hidden_BaseUrl = v
}

func (x *GrpcClient) SetApiKey(v string) {
	x.xxx_hidden_ApiKey = v
}

func (x *GrpcClient) SetApiKeyHeader(v string) {
	x.xxx_hidden_ApiKeyHeader = v
}

type GrpcClient_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier for this client.
	Name string
	// Base URL of the gRPC service.
	BaseUrl string
	// API key for authentication.
	ApiKey string
	// API key header for authentication.
	ApiKeyHeader string
}

func (b0 GrpcClient_builder) Build() *GrpcClient {
	m0 := &GrpcClient{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_BaseUrl = b.BaseUrl
	x.xxx_hidden_ApiKey = b.ApiKey
	x.xxx_hidden_ApiKeyHeader = b.ApiKeyHeader
	return m0
}

// A model with an optional alias for convenience.
type Model struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name  string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Alias string                 `protobuf:"bytes,2,opt,name=alias,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_sgpt_v1_configuration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_configuration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Model) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Model) GetAlias() string {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return ""
}

func (x *Model) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Model) SetAlias(v string) {
	x.xxx_hidden_Alias = v
}

type Model_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The resource name of the model.
	// Format: providers/{provider}/models/{model}
	Name string
	// Short alias for the model.
	Alias string
}

func (b0 Model_builder) Build() *Model {
	m0 := &Model{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Alias = b.Alias
	return m0
}

// Chat-specific configuration.
type ChatConfiguration struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_User         string                 `protobuf:"bytes,1,opt,name=user,proto3"`
	xxx_hidden_SummaryModel string                 `protobuf:"bytes,2,opt,name=summary_model,json=summaryModel,proto3"`
	xxx_hidden_DefaultModel string                 `protobuf:"bytes,3,opt,name=default_model,json=defaultModel,proto3"`
	xxx_hidden_DefaultRole  string                 `protobuf:"bytes,4,opt,name=default_role,json=defaultRole,proto3"`
	xxx_hidden_DefaultTools []string               `protobuf:"bytes,5,rep,name=default_tools,json=defaultTools,proto3"`
	xxx_hidden_DefaultLores []string               `protobuf:"bytes,6,rep,name=default_lores,json=defaultLores,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ChatConfiguration) Reset() {
	*x = ChatConfiguration{}
	mi := &file_sgpt_v1_configuration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatConfiguration) ProtoMessage() {}

func (x *ChatConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_configuration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ChatConfiguration) GetUser() string {
	if x != nil {
		return x.xxx_hidden_User
	}
	return ""
}

func (x *ChatConfiguration) GetSummaryModel() string {
	if x != nil {
		return x.xxx_hidden_SummaryModel
	}
	return ""
}

func (x *ChatConfiguration) GetDefaultModel() string {
	if x != nil {
		return x.xxx_hidden_DefaultModel
	}
	return ""
}

func (x *ChatConfiguration) GetDefaultRole() string {
	if x != nil {
		return x.xxx_hidden_DefaultRole
	}
	return ""
}

func (x *ChatConfiguration) GetDefaultTools() []string {
	if x != nil {
		return x.xxx_hidden_DefaultTools
	}
	return nil
}

func (x *ChatConfiguration) GetDefaultLores() []string {
	if x != nil {
		return x.xxx_hidden_DefaultLores
	}
	return nil
}

func (x *ChatConfiguration) SetUser(v string) {
	x.xxx_hidden_User = v
}

func (x *ChatConfiguration) SetSummaryModel(v string) {
	x.xxx_hidden_SummaryModel = v
}

func (x *ChatConfiguration) SetDefaultModel(v string) {
	x.xxx_hidden_DefaultModel = v
}

func (x *ChatConfiguration) SetDefaultRole(v string) {
	x.xxx_hidden_DefaultRole = v
}

func (x *ChatConfiguration) SetDefaultTools(v []string) {
	x.xxx_hidden_DefaultTools = v
}

func (x *ChatConfiguration) SetDefaultLores(v []string) {
	x.xxx_hidden_DefaultLores = v
}

type ChatConfiguration_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The user under which chats are created and listed.
	// Format: organizations/{organization}/users/{user}
	User string
	// The resource name of the model used to generate summaries.
	// Format: providers/{provider}/models/{model}
	SummaryModel string
	// The resource name of the default model.
	// Format: providers/{provider}/models/{model}
	DefaultModel string
	// The default role selector (e.g. "//path/to:role" or a root role title).
	DefaultRole string
	// Tools advertised to the model in every chat, on top of those requested
	// by the role and --tool (e.g. "search_lores").
	DefaultTools []string
	// Lores injected into the context of every chat, as selectors
	// ("lores/{lore}" locally, "@{import}//lores/{lore}" for an imported
	// repo). Selectors rather than paths, so a lore survives being moved.
	DefaultLores []string
}

func (b0 ChatConfiguration_builder) Build() *ChatConfiguration {
	m0 := &ChatConfiguration{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_User = b.User
	x.xxx_hidden_SummaryModel = b.SummaryModel
	x.xxx_hidden_DefaultModel = b.DefaultModel
	x.xxx_hidden_DefaultRole = b.DefaultRole
	x.xxx_hidden_DefaultTools = b.DefaultTools
	x.xxx_hidden_DefaultLores = b.DefaultLores
	return m0
}

// A role defines a persona with a system prompt. Persisted as a
// `.sgpt/{title}.role.md` markdown file — `@directive(...)` lines carry the
// structured fields, the body is the prompt — and addressed please-style
// ("//dir:title", "@import//dir:title").
type Role struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name   string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Alias  string                 `protobuf:"bytes,2,opt,name=alias,proto3"`
	xxx_hidden_Prompt string                 `protobuf:"bytes,3,opt,name=prompt,proto3"`
	xxx_hidden_Model  string                 `protobuf:"bytes,4,opt,name=model,proto3"`
	xxx_hidden_Files  []string               `protobuf:"bytes,5,rep,name=files,proto3"`
	xxx_hidden_Tools  []string               `protobuf:"bytes,6,rep,name=tools,proto3"`
	xxx_hidden_Roles  []string               `protobuf:"bytes,7,rep,name=roles,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_sgpt_v1_configuration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_configuration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Role) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Role) GetAlias() string {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return ""
}

func (x *Role) GetPrompt() string {
	if x != nil {
		return x.xxx_hidden_Prompt
	}
	return ""
}

func (x *Role) GetModel() string {
	if x != nil {
		return x.xxx_hidden_Model
	}
	return ""
}

func (x *Role) GetFiles() []string {
	if x != nil {
		return x.xxx_hidden_Files
	}
	return nil
}

func (x *Role) GetTools() []string {
	if x != nil {
		return x.xxx_hidden_Tools
	}
	return nil
}

func (x *Role) GetRoles() []string {
	if x != nil {
		return x.xxx_hidden_Roles
	}
	return nil
}

func (x *Role) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Role) SetAlias(v string) {
	x.xxx_hidden_Alias = v
}

func (x *Role) SetPrompt(v string) {
	x.xxx_hidden_Prompt = v
}

func (x *Role) SetModel(v string) {
	x.xxx_hidden_Model = v
}

func (x *Role) SetFiles(v []string) {
	x.xxx_hidden_Files = v
}

func (x *Role) SetTools(v []string) {
	x.xxx_hidden_Tools = v
}

func (x *Role) SetRoles(v []string) {
	x.xxx_hidden_Roles = v
}

type Role_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Name of this role: its selector ("//dir:title"), derived from the file
	// location. Never written in the file.
	Name string
	// Short alias for this role (`@alias("go")`).
	Alias string
	// System prompt for this role: the markdown body.
	Prompt string
	// The resource name of the model to use for this role (`@model("...")`).
	// Format: providers/{provider}/models/{model}
	Model string
	// Files to include as context for this role (`@file("path")`).
	Files []string
	// Tools to include as part of this role (`@tool("exec_shell")`).
	Tools []string
	// Selectors of other roles to include (`@role("//dir:title")`). Included
	// roles are expanded depth-first: their prompts are prepended and their
	// files/tools merged.
	Roles []string
}

func (b0 Role_builder) Build() *Role {
	m0 := &Role{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Alias = b.Alias
	x.xxx_hidden_Prompt = b.Prompt
	x.xxx_hidden_Model = b.Model
	x.xxx_hidden_Files = b.Files
	x.xxx_hidden_Tools = b.Tools
	x.xxx_hidden_Roles = b.Roles
	return m0
}

// A remote tool engine that provides tool sets via gRPC. Persisted as a
// `.sgpt/{title}.toolset` file; discovered and addressed please-style
// ("//dir:title", "@import//dir:title").
type ToolSet struct {
	state                    protoimpl.MessageState             `protogen:"opaque.v1"`
	xxx_hidden_Name          string                             `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_EngineService string                             `protobuf:"bytes,2,opt,name=engine_service,json=engineService,proto3"`
	xxx_hidden_ToolSets      *[]*v1.CreateServiceToolSetRequest `protobuf:"bytes,3,rep,name=tool_sets,json=toolSets,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ToolSet) Reset() {
	*x = ToolSet{}
	mi := &file_sgpt_v1_configuration_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolSet) ProtoMessage() {}

func (x *ToolSet) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_configuration_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ToolSet) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *ToolSet) GetEngineService() string {
	if x != nil {
		return x.xxx_hidden_EngineService
	}
	return ""
}

func (x *ToolSet) GetToolSets() []*v1.CreateServiceToolSetRequest {
	if x != nil {
		if x.xxx_hidden_ToolSets != nil {
			return *x.xxx_hidden_ToolSets
		}
	}
	return nil
}

func (x *ToolSet) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *ToolSet) SetEngineService(v string) {
	x.xxx_hidden_EngineService = v
}

func (x *ToolSet) SetToolSets(v []*v1.CreateServiceToolSetRequest) {
	x.xxx_hidden_ToolSets = &v
}

type ToolSet_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Name of this tool set: its selector ("//dir:title"). Maintained by
	// sgpt, never read from the file.
	Name string
	// Name of the gRPC client to use for the engine service.
	EngineService string
	// Tool set definitions to create from this engine.
	ToolSets []*v1.CreateServiceToolSetRequest
}

func (b0 ToolSet_builder) Build() *ToolSet {
	m0 := &ToolSet{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_EngineService = b.EngineService
	x.xxx_hidden_ToolSets = &b.ToolSets
	return m0
}

var File_sgpt_v1_configuration_proto protoreflect.FileDescriptor

const file_sgpt_v1_configuration_proto_rawDesc = "" +
	"\n" +
	"\x1bsgpt/v1/configuration.proto\x12\asgpt.v1\x1a\x1bbuf/validate/validate.proto\x1a\x19google/api/resource.proto\x1a'malonaz/ai/ai_engine/v1/ai_engine.proto\"\x97\x02\n" +
	"\rConfiguration\x126\n" +
	"\fgrpc_clients\x18\x01 \x03(\v2\x13.sgpt.v1.GrpcClientR\vgrpcClients\x12\x1d\n" +
	"\n" +
	"ai_service\x18\x02 \x01(\tR\taiService\x12&\n" +
	"\x06models\x18\x03 \x03(\v2\x0e.sgpt.v1.ModelR\x06models\x12.\n" +
	"\x04chat\x18\x04 \x01(\v2\x1a.sgpt.v1.ChatConfigurationR\x04chat\x12\x16\n" +
	"\x06ignore\x18\x06 \x03(\tR\x06ignore\x12\x14\n" +
	"\x05title\x18\a \x01(\tR\x05title\x12)\n" +
	"\aimports\x18\b \x03(\v2\x0f.sgpt.v1.ImportR\aimports\"@\n" +
	"\x06Import\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\x12\x1a\n" +
	"\x04path\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04path\"\x8a\x01\n" +
	"\n" +
	"GrpcClient\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\x12!\n" +
	"\bbase_url\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\abaseUrl\x12\x17\n" +
	"\aapi_key\x18\x03 \x01(\tR\x06apiKey\x12$\n" +
	"\x0eapi_key_header\x18\x04 \x01(\tR\fapiKeyHeader\"R\n" +
	"\x05Model\x123\n" +
	"\x04name\x18\x01 \x01(\tB\x1f\xfaA\x16\n" +
	"\x14ai.malonaz.com/Model\xbaH\x03\xc8\x01\x01R\x04name\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\"\xae\x02\n" +
	"\x11ChatConfiguration\x12,\n" +
	"\x04user\x18\x01 \x01(\tB\x18\xfaA\x15\n" +
	"\x13ai.malonaz.com/UserR\x04user\x12>\n" +
	"\rsummary_model\x18\x02 \x01(\tB\x19\xfaA\x16\n" +
	"\x14ai.malonaz.com/ModelR\fsummaryModel\x12>\n" +
	"\rdefault_model\x18\x03 \x01(\tB\x19\xfaA\x16\n" +
	"\x14ai.malonaz.com/ModelR\fdefaultModel\x12!\n" +
	"\fdefault_role\x18\x04 \x01(\tR\vdefaultRole\x12#\n" +
	"\rdefault_tools\x18\x05 \x03(\tR\fdefaultTools\x12#\n" +
	"\rdefault_lores\x18\x06 \x03(\tR\fdefaultLores\"\xc1\x01\n" +
	"\x04Role\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x12/\n" +
	"\x05model\x18\x04 \x01(\tB\x19\xfaA\x16\n" +
	"\x14ai.malonaz.com/ModelR\x05model\x12\x14\n" +
	"\x05files\x18\x05 \x03(\tR\x05files\x12\x14\n" +
	"\x05tools\x18\x06 \x03(\tR\x05tools\x12\x14\n" +
	"\x05roles\x18\a \x03(\tR\x05rolesJ\x04\b\b\x10\t\"\x9f\x01\n" +
	"\aToolSet\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12-\n" +
	"\x0eengine_service\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\rengineService\x12Q\n" +
	"\ttool_sets\x18\x03 \x03(\v24.malonaz.ai.ai_engine.v1.CreateServiceToolSetRequestR\btoolSetsB*Z(github.com/malonaz/sgpt/genproto/sgpt/v1b\x06proto3"

var file_sgpt_v1_configuration_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_sgpt_v1_configuration_proto_goTypes = []any{
	(*Configuration)(nil),                  // 0: sgpt.v1.Configuration
	(*Import)(nil),                         // 1: sgpt.v1.Import
	(*GrpcClient)(nil),                     // 2: sgpt.v1.GrpcClient
	(*Model)(nil),                          // 3: sgpt.v1.Model
	(*ChatConfiguration)(nil),              // 4: sgpt.v1.ChatConfiguration
	(*Role)(nil),                           // 5: sgpt.v1.Role
	(*ToolSet)(nil),                        // 6: sgpt.v1.ToolSet
	(*v1.CreateServiceToolSetRequest)(nil), // 7: malonaz.ai.ai_engine.v1.CreateServiceToolSetRequest
}
var file_sgpt_v1_configuration_proto_depIdxs = []int32{
	2, // 0: sgpt.v1.Configuration.grpc_clients:type_name -> sgpt.v1.GrpcClient
	3, // 1: sgpt.v1.Configuration.models:type_name -> sgpt.v1.Model
	4, // 2: sgpt.v1.Configuration.chat:type_name -> sgpt.v1.ChatConfiguration
	1, // 3: sgpt.v1.Configuration.imports:type_name -> sgpt.v1.Import
	7, // 4: sgpt.v1.ToolSet.tool_sets:type_name -> malonaz.ai.ai_engine.v1.CreateServiceToolSetRequest
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_sgpt_v1_configuration_proto_init() }
func file_sgpt_v1_configuration_proto_init() {
	if File_sgpt_v1_configuration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sgpt_v1_configuration_proto_rawDesc), len(file_sgpt_v1_configuration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sgpt_v1_configuration_proto_goTypes,
		DependencyIndexes: file_sgpt_v1_configuration_proto_depIdxs,
		MessageInfos:      file_sgpt_v1_configuration_proto_msgTypes,
	}.Build()
	File_sgpt_v1_configuration_proto = out.File
	file_sgpt_v1_configuration_proto_goTypes = nil
	file_sgpt_v1_configuration_proto_depIdxs = nil
}
