// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: sgpt/v1/configuration.proto

//go:build !protoopaque

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Configuration for the sgpt tool.
type Configuration struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// gRPC client configuration for the chat service.
	ChatService *GRPCClient `protobuf:"bytes,1,opt,name=chat_service,json=chatService,proto3" json:"chat_service,omitempty"`
	// gRPC client configuration for the AI service.
	AiService *GRPCClient `protobuf:"bytes,2,opt,name=ai_service,json=aiService,proto3" json:"ai_service,omitempty"`
	// Available models.
	Models []*Model `protobuf:"bytes,3,rep,name=models,proto3" json:"models,omitempty"`
	// Chat configuration.
	Chat          *ChatConfiguration `protobuf:"bytes,4,opt,name=chat,proto3" json:"chat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Configuration) Reset() {
	*x = Configuration{}
	mi := &file_sgpt_v1_configuration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration) ProtoMessage() {}

func (x *Configuration) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_configuration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Configuration) GetChatService() *GRPCClient {
	if x != nil {
		return x.ChatService
	}
	return nil
}

func (x *Configuration) GetAiService() *GRPCClient {
	if x != nil {
		return x.AiService
	}
	return nil
}

func (x *Configuration) GetModels() []*Model {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *Configuration) GetChat() *ChatConfiguration {
	if x != nil {
		return x.Chat
	}
	return nil
}

func (x *Configuration) SetChatService(v *GRPCClient) {
	x.ChatService = v
}

func (x *Configuration) SetAiService(v *GRPCClient) {
	x.AiService = v
}

func (x *Configuration) SetModels(v []*Model) {
	x.Models = v
}

func (x *Configuration) SetChat(v *ChatConfiguration) {
	x.Chat = v
}

func (x *Configuration) HasChatService() bool {
	if x == nil {
		return false
	}
	return x.ChatService != nil
}

func (x *Configuration) HasAiService() bool {
	if x == nil {
		return false
	}
	return x.AiService != nil
}

func (x *Configuration) HasChat() bool {
	if x == nil {
		return false
	}
	return x.Chat != nil
}

func (x *Configuration) ClearChatService() {
	x.ChatService = nil
}

func (x *Configuration) ClearAiService() {
	x.AiService = nil
}

func (x *Configuration) ClearChat() {
	x.Chat = nil
}

type Configuration_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// gRPC client configuration for the chat service.
	ChatService *GRPCClient
	// gRPC client configuration for the AI service.
	AiService *GRPCClient
	// Available models.
	Models []*Model
	// Chat configuration.
	Chat *ChatConfiguration
}

func (b0 Configuration_builder) Build() *Configuration {
	m0 := &Configuration{}
	b, x := &b0, m0
	_, _ = b, x
	x.ChatService = b.ChatService
	x.AiService = b.AiService
	x.Models = b.Models
	x.Chat = b.Chat
	return m0
}

// gRPC client configuration.
type GRPCClient struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Base URL of the gRPC service.
	BaseUrl string `protobuf:"bytes,1,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	// API key for authentication.
	ApiKey        string `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GRPCClient) Reset() {
	*x = GRPCClient{}
	mi := &file_sgpt_v1_configuration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GRPCClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRPCClient) ProtoMessage() {}

func (x *GRPCClient) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_configuration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GRPCClient) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *GRPCClient) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *GRPCClient) SetBaseUrl(v string) {
	x.BaseUrl = v
}

func (x *GRPCClient) SetApiKey(v string) {
	x.ApiKey = v
}

type GRPCClient_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Base URL of the gRPC service.
	BaseUrl string
	// API key for authentication.
	ApiKey string
}

func (b0 GRPCClient_builder) Build() *GRPCClient {
	m0 := &GRPCClient{}
	b, x := &b0, m0
	_, _ = b, x
	x.BaseUrl = b.BaseUrl
	x.ApiKey = b.ApiKey
	return m0
}

// A model with an optional alias for convenience.
type Model struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// The resource name of the model.
	// Format: providers/{provider}/models/{model}
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Short alias for the model.
	Alias         string `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_sgpt_v1_configuration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_configuration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Model) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Model) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *Model) SetName(v string) {
	x.Name = v
}

func (x *Model) SetAlias(v string) {
	x.Alias = v
}

type Model_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The resource name of the model.
	// Format: providers/{provider}/models/{model}
	Name string
	// Short alias for the model.
	Alias string
}

func (b0 Model_builder) Build() *Model {
	m0 := &Model{}
	b, x := &b0, m0
	_, _ = b, x
	x.Name = b.Name
	x.Alias = b.Alias
	return m0
}

// Chat-specific configuration.
type ChatConfiguration struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// The resource name of the model used to generate summaries.
	// Format: providers/{provider}/models/{model}
	SummaryModel string `protobuf:"bytes,1,opt,name=summary_model,json=summaryModel,proto3" json:"summary_model,omitempty"`
	// The resource name of the default model.
	// Format: providers/{provider}/models/{model}
	DefaultModel string `protobuf:"bytes,2,opt,name=default_model,json=defaultModel,proto3" json:"default_model,omitempty"`
	// The default role alias or name.
	DefaultRole string `protobuf:"bytes,3,opt,name=default_role,json=defaultRole,proto3" json:"default_role,omitempty"`
	// User-defined roles.
	Roles         []*Role `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatConfiguration) Reset() {
	*x = ChatConfiguration{}
	mi := &file_sgpt_v1_configuration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatConfiguration) ProtoMessage() {}

func (x *ChatConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_configuration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ChatConfiguration) GetSummaryModel() string {
	if x != nil {
		return x.SummaryModel
	}
	return ""
}

func (x *ChatConfiguration) GetDefaultModel() string {
	if x != nil {
		return x.DefaultModel
	}
	return ""
}

func (x *ChatConfiguration) GetDefaultRole() string {
	if x != nil {
		return x.DefaultRole
	}
	return ""
}

func (x *ChatConfiguration) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ChatConfiguration) SetSummaryModel(v string) {
	x.SummaryModel = v
}

func (x *ChatConfiguration) SetDefaultModel(v string) {
	x.DefaultModel = v
}

func (x *ChatConfiguration) SetDefaultRole(v string) {
	x.DefaultRole = v
}

func (x *ChatConfiguration) SetRoles(v []*Role) {
	x.Roles = v
}

type ChatConfiguration_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The resource name of the model used to generate summaries.
	// Format: providers/{provider}/models/{model}
	SummaryModel string
	// The resource name of the default model.
	// Format: providers/{provider}/models/{model}
	DefaultModel string
	// The default role alias or name.
	DefaultRole string
	// User-defined roles.
	Roles []*Role
}

func (b0 ChatConfiguration_builder) Build() *ChatConfiguration {
	m0 := &ChatConfiguration{}
	b, x := &b0, m0
	_, _ = b, x
	x.SummaryModel = b.SummaryModel
	x.DefaultModel = b.DefaultModel
	x.DefaultRole = b.DefaultRole
	x.Roles = b.Roles
	return m0
}

// A role defines a persona with a system prompt.
type Role struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Name of this role.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Short alias for this role.
	Alias string `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	// System prompt for this role.
	Prompt string `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	// The resource name of the model to use for this role.
	// Format: providers/{provider}/models/{model}
	Model string `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	// Files to include as context for this role.
	Files         []string `protobuf:"bytes,5,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_sgpt_v1_configuration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_configuration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *Role) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *Role) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Role) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *Role) SetName(v string) {
	x.Name = v
}

func (x *Role) SetAlias(v string) {
	x.Alias = v
}

func (x *Role) SetPrompt(v string) {
	x.Prompt = v
}

func (x *Role) SetModel(v string) {
	x.Model = v
}

func (x *Role) SetFiles(v []string) {
	x.Files = v
}

type Role_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Name of this role.
	Name string
	// Short alias for this role.
	Alias string
	// System prompt for this role.
	Prompt string
	// The resource name of the model to use for this role.
	// Format: providers/{provider}/models/{model}
	Model string
	// Files to include as context for this role.
	Files []string
}

func (b0 Role_builder) Build() *Role {
	m0 := &Role{}
	b, x := &b0, m0
	_, _ = b, x
	x.Name = b.Name
	x.Alias = b.Alias
	x.Prompt = b.Prompt
	x.Model = b.Model
	x.Files = b.Files
	return m0
}

var File_sgpt_v1_configuration_proto protoreflect.FileDescriptor

const file_sgpt_v1_configuration_proto_rawDesc = "" +
	"\n" +
	"\x1bsgpt/v1/configuration.proto\x12\asgpt.v1\x1a\x1bbuf/validate/validate.proto\x1a\x19google/api/resource.proto\"\xd3\x01\n" +
	"\rConfiguration\x126\n" +
	"\fchat_service\x18\x01 \x01(\v2\x13.sgpt.v1.GRPCClientR\vchatService\x122\n" +
	"\n" +
	"ai_service\x18\x02 \x01(\v2\x13.sgpt.v1.GRPCClientR\taiService\x12&\n" +
	"\x06models\x18\x03 \x03(\v2\x0e.sgpt.v1.ModelR\x06models\x12.\n" +
	"\x04chat\x18\x04 \x01(\v2\x1a.sgpt.v1.ChatConfigurationR\x04chat\"H\n" +
	"\n" +
	"GRPCClient\x12!\n" +
	"\bbase_url\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\abaseUrl\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\"R\n" +
	"\x05Model\x123\n" +
	"\x04name\x18\x01 \x01(\tB\x1f\xfaA\x16\n" +
	"\x14ai.malonaz.com/Model\xbaH\x03\xc8\x01\x01R\x04name\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\"\xdb\x01\n" +
	"\x11ChatConfiguration\x12>\n" +
	"\rsummary_model\x18\x01 \x01(\tB\x19\xfaA\x16\n" +
	"\x14ai.malonaz.com/ModelR\fsummaryModel\x12>\n" +
	"\rdefault_model\x18\x02 \x01(\tB\x19\xfaA\x16\n" +
	"\x14ai.malonaz.com/ModelR\fdefaultModel\x12!\n" +
	"\fdefault_role\x18\x03 \x01(\tR\vdefaultRole\x12#\n" +
	"\x05roles\x18\x04 \x03(\v2\r.sgpt.v1.RoleR\x05roles\"\x9f\x01\n" +
	"\x04Role\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12\x1e\n" +
	"\x06prompt\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x06prompt\x12/\n" +
	"\x05model\x18\x04 \x01(\tB\x19\xfaA\x16\n" +
	"\x14ai.malonaz.com/ModelR\x05model\x12\x14\n" +
	"\x05files\x18\x05 \x03(\tR\x05filesB*Z(github.com/malonaz/sgpt/genproto/sgpt/v1b\x06proto3"

var file_sgpt_v1_configuration_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sgpt_v1_configuration_proto_goTypes = []any{
	(*Configuration)(nil),     // 0: sgpt.v1.Configuration
	(*GRPCClient)(nil),        // 1: sgpt.v1.GRPCClient
	(*Model)(nil),             // 2: sgpt.v1.Model
	(*ChatConfiguration)(nil), // 3: sgpt.v1.ChatConfiguration
	(*Role)(nil),              // 4: sgpt.v1.Role
}
var file_sgpt_v1_configuration_proto_depIdxs = []int32{
	1, // 0: sgpt.v1.Configuration.chat_service:type_name -> sgpt.v1.GRPCClient
	1, // 1: sgpt.v1.Configuration.ai_service:type_name -> sgpt.v1.GRPCClient
	2, // 2: sgpt.v1.Configuration.models:type_name -> sgpt.v1.Model
	3, // 3: sgpt.v1.Configuration.chat:type_name -> sgpt.v1.ChatConfiguration
	4, // 4: sgpt.v1.ChatConfiguration.roles:type_name -> sgpt.v1.Role
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_sgpt_v1_configuration_proto_init() }
func file_sgpt_v1_configuration_proto_init() {
	if File_sgpt_v1_configuration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sgpt_v1_configuration_proto_rawDesc), len(file_sgpt_v1_configuration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sgpt_v1_configuration_proto_goTypes,
		DependencyIndexes: file_sgpt_v1_configuration_proto_depIdxs,
		MessageInfos:      file_sgpt_v1_configuration_proto_msgTypes,
	}.Build()
	File_sgpt_v1_configuration_proto = out.File
	file_sgpt_v1_configuration_proto_goTypes = nil
	file_sgpt_v1_configuration_proto_depIdxs = nil
}
