// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: sgpt/v1/configuration.proto

//go:build protoopaque

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/malonaz/core/genproto/ai/ai_engine/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Configuration for the sgpt tool.
type Configuration struct {
	state                  protoimpl.MessageState      `protogen:"opaque.v1"`
	xxx_hidden_SgptService *GRPCClient                 `protobuf:"bytes,1,opt,name=sgpt_service,json=sgptService,proto3"`
	xxx_hidden_AiService   *GRPCClient                 `protobuf:"bytes,2,opt,name=ai_service,json=aiService,proto3"`
	xxx_hidden_Models      *[]*Model                   `protobuf:"bytes,3,rep,name=models,proto3"`
	xxx_hidden_Chat        *ChatConfiguration          `protobuf:"bytes,4,opt,name=chat,proto3"`
	xxx_hidden_ToolEngines *[]*ToolEngineConfiguration `protobuf:"bytes,5,rep,name=tool_engines,json=toolEngines,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Configuration) Reset() {
	*x = Configuration{}
	mi := &file_sgpt_v1_configuration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration) ProtoMessage() {}

func (x *Configuration) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_configuration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Configuration) GetSgptService() *GRPCClient {
	if x != nil {
		return x.xxx_hidden_SgptService
	}
	return nil
}

func (x *Configuration) GetAiService() *GRPCClient {
	if x != nil {
		return x.xxx_hidden_AiService
	}
	return nil
}

func (x *Configuration) GetModels() []*Model {
	if x != nil {
		if x.xxx_hidden_Models != nil {
			return *x.xxx_hidden_Models
		}
	}
	return nil
}

func (x *Configuration) GetChat() *ChatConfiguration {
	if x != nil {
		return x.xxx_hidden_Chat
	}
	return nil
}

func (x *Configuration) GetToolEngines() []*ToolEngineConfiguration {
	if x != nil {
		if x.xxx_hidden_ToolEngines != nil {
			return *x.xxx_hidden_ToolEngines
		}
	}
	return nil
}

func (x *Configuration) SetSgptService(v *GRPCClient) {
	x.xxx_hidden_SgptService = v
}

func (x *Configuration) SetAiService(v *GRPCClient) {
	x.xxx_hidden_AiService = v
}

func (x *Configuration) SetModels(v []*Model) {
	x.xxx_hidden_Models = &v
}

func (x *Configuration) SetChat(v *ChatConfiguration) {
	x.xxx_hidden_Chat = v
}

func (x *Configuration) SetToolEngines(v []*ToolEngineConfiguration) {
	x.xxx_hidden_ToolEngines = &v
}

func (x *Configuration) HasSgptService() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SgptService != nil
}

func (x *Configuration) HasAiService() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AiService != nil
}

func (x *Configuration) HasChat() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Chat != nil
}

func (x *Configuration) ClearSgptService() {
	x.xxx_hidden_SgptService = nil
}

func (x *Configuration) ClearAiService() {
	x.xxx_hidden_AiService = nil
}

func (x *Configuration) ClearChat() {
	x.xxx_hidden_Chat = nil
}

type Configuration_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// gRPC client configuration for the chat service.
	SgptService *GRPCClient
	// gRPC client configuration for the AI service.
	AiService *GRPCClient
	// Available models.
	Models []*Model
	// Chat configuration.
	Chat *ChatConfiguration
	// Tool engine configurations. Each entry defines a remote gRPC service
	// that provides tool sets for AI interactions.
	ToolEngines []*ToolEngineConfiguration
}

func (b0 Configuration_builder) Build() *Configuration {
	m0 := &Configuration{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SgptService = b.SgptService
	x.xxx_hidden_AiService = b.AiService
	x.xxx_hidden_Models = &b.Models
	x.xxx_hidden_Chat = b.Chat
	x.xxx_hidden_ToolEngines = &b.ToolEngines
	return m0
}

// gRPC client configuration.
type GRPCClient struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_BaseUrl      string                 `protobuf:"bytes,1,opt,name=base_url,json=baseUrl,proto3"`
	xxx_hidden_ApiKey       string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3"`
	xxx_hidden_ApiKeyHeader string                 `protobuf:"bytes,3,opt,name=api_key_header,json=apiKeyHeader,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GRPCClient) Reset() {
	*x = GRPCClient{}
	mi := &file_sgpt_v1_configuration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GRPCClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRPCClient) ProtoMessage() {}

func (x *GRPCClient) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_configuration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GRPCClient) GetBaseUrl() string {
	if x != nil {
		return x.xxx_hidden_BaseUrl
	}
	return ""
}

func (x *GRPCClient) GetApiKey() string {
	if x != nil {
		return x.xxx_hidden_ApiKey
	}
	return ""
}

func (x *GRPCClient) GetApiKeyHeader() string {
	if x != nil {
		return x.xxx_hidden_ApiKeyHeader
	}
	return ""
}

func (x *GRPCClient) SetBaseUrl(v string) {
	x.xxx_hidden_BaseUrl = v
}

func (x *GRPCClient) SetApiKey(v string) {
	x.xxx_hidden_ApiKey = v
}

func (x *GRPCClient) SetApiKeyHeader(v string) {
	x.xxx_hidden_ApiKeyHeader = v
}

type GRPCClient_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Base URL of the gRPC service.
	BaseUrl string
	// API key for authentication.
	ApiKey string
	// API key header for authentication.
	ApiKeyHeader string
}

func (b0 GRPCClient_builder) Build() *GRPCClient {
	m0 := &GRPCClient{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_BaseUrl = b.BaseUrl
	x.xxx_hidden_ApiKey = b.ApiKey
	x.xxx_hidden_ApiKeyHeader = b.ApiKeyHeader
	return m0
}

// A model with an optional alias for convenience.
type Model struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name  string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Alias string                 `protobuf:"bytes,2,opt,name=alias,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_sgpt_v1_configuration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_configuration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Model) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Model) GetAlias() string {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return ""
}

func (x *Model) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Model) SetAlias(v string) {
	x.xxx_hidden_Alias = v
}

type Model_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The resource name of the model.
	// Format: providers/{provider}/models/{model}
	Name string
	// Short alias for the model.
	Alias string
}

func (b0 Model_builder) Build() *Model {
	m0 := &Model{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Alias = b.Alias
	return m0
}

// Chat-specific configuration.
type ChatConfiguration struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SummaryModel string                 `protobuf:"bytes,1,opt,name=summary_model,json=summaryModel,proto3"`
	xxx_hidden_DefaultModel string                 `protobuf:"bytes,2,opt,name=default_model,json=defaultModel,proto3"`
	xxx_hidden_DefaultRole  string                 `protobuf:"bytes,3,opt,name=default_role,json=defaultRole,proto3"`
	xxx_hidden_Roles        *[]*Role               `protobuf:"bytes,4,rep,name=roles,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ChatConfiguration) Reset() {
	*x = ChatConfiguration{}
	mi := &file_sgpt_v1_configuration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatConfiguration) ProtoMessage() {}

func (x *ChatConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_configuration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ChatConfiguration) GetSummaryModel() string {
	if x != nil {
		return x.xxx_hidden_SummaryModel
	}
	return ""
}

func (x *ChatConfiguration) GetDefaultModel() string {
	if x != nil {
		return x.xxx_hidden_DefaultModel
	}
	return ""
}

func (x *ChatConfiguration) GetDefaultRole() string {
	if x != nil {
		return x.xxx_hidden_DefaultRole
	}
	return ""
}

func (x *ChatConfiguration) GetRoles() []*Role {
	if x != nil {
		if x.xxx_hidden_Roles != nil {
			return *x.xxx_hidden_Roles
		}
	}
	return nil
}

func (x *ChatConfiguration) SetSummaryModel(v string) {
	x.xxx_hidden_SummaryModel = v
}

func (x *ChatConfiguration) SetDefaultModel(v string) {
	x.xxx_hidden_DefaultModel = v
}

func (x *ChatConfiguration) SetDefaultRole(v string) {
	x.xxx_hidden_DefaultRole = v
}

func (x *ChatConfiguration) SetRoles(v []*Role) {
	x.xxx_hidden_Roles = &v
}

type ChatConfiguration_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The resource name of the model used to generate summaries.
	// Format: providers/{provider}/models/{model}
	SummaryModel string
	// The resource name of the default model.
	// Format: providers/{provider}/models/{model}
	DefaultModel string
	// The default role alias or name.
	DefaultRole string
	// User-defined roles.
	Roles []*Role
}

func (b0 ChatConfiguration_builder) Build() *ChatConfiguration {
	m0 := &ChatConfiguration{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SummaryModel = b.SummaryModel
	x.xxx_hidden_DefaultModel = b.DefaultModel
	x.xxx_hidden_DefaultRole = b.DefaultRole
	x.xxx_hidden_Roles = &b.Roles
	return m0
}

// A role defines a persona with a system prompt.
type Role struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name   string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Alias  string                 `protobuf:"bytes,2,opt,name=alias,proto3"`
	xxx_hidden_Prompt string                 `protobuf:"bytes,3,opt,name=prompt,proto3"`
	xxx_hidden_Model  string                 `protobuf:"bytes,4,opt,name=model,proto3"`
	xxx_hidden_Files  []string               `protobuf:"bytes,5,rep,name=files,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_sgpt_v1_configuration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_configuration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Role) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Role) GetAlias() string {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return ""
}

func (x *Role) GetPrompt() string {
	if x != nil {
		return x.xxx_hidden_Prompt
	}
	return ""
}

func (x *Role) GetModel() string {
	if x != nil {
		return x.xxx_hidden_Model
	}
	return ""
}

func (x *Role) GetFiles() []string {
	if x != nil {
		return x.xxx_hidden_Files
	}
	return nil
}

func (x *Role) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Role) SetAlias(v string) {
	x.xxx_hidden_Alias = v
}

func (x *Role) SetPrompt(v string) {
	x.xxx_hidden_Prompt = v
}

func (x *Role) SetModel(v string) {
	x.xxx_hidden_Model = v
}

func (x *Role) SetFiles(v []string) {
	x.xxx_hidden_Files = v
}

type Role_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Name of this role.
	Name string
	// Short alias for this role.
	Alias string
	// System prompt for this role.
	Prompt string
	// The resource name of the model to use for this role.
	// Format: providers/{provider}/models/{model}
	Model string
	// Files to include as context for this role.
	Files []string
}

func (b0 Role_builder) Build() *Role {
	m0 := &Role{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Alias = b.Alias
	x.xxx_hidden_Prompt = b.Prompt
	x.xxx_hidden_Model = b.Model
	x.xxx_hidden_Files = b.Files
	return m0
}

// Configuration for a remote tool engine that provides tool sets via gRPC.
type ToolEngineConfiguration struct {
	state                    protoimpl.MessageState             `protogen:"opaque.v1"`
	xxx_hidden_Name          string                             `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_EngineService *GRPCClient                        `protobuf:"bytes,2,opt,name=engine_service,json=engineService,proto3"`
	xxx_hidden_ToolSets      *[]*v1.CreateServiceToolSetRequest `protobuf:"bytes,3,rep,name=tool_sets,json=toolSets,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ToolEngineConfiguration) Reset() {
	*x = ToolEngineConfiguration{}
	mi := &file_sgpt_v1_configuration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolEngineConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolEngineConfiguration) ProtoMessage() {}

func (x *ToolEngineConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_configuration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ToolEngineConfiguration) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *ToolEngineConfiguration) GetEngineService() *GRPCClient {
	if x != nil {
		return x.xxx_hidden_EngineService
	}
	return nil
}

func (x *ToolEngineConfiguration) GetToolSets() []*v1.CreateServiceToolSetRequest {
	if x != nil {
		if x.xxx_hidden_ToolSets != nil {
			return *x.xxx_hidden_ToolSets
		}
	}
	return nil
}

func (x *ToolEngineConfiguration) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *ToolEngineConfiguration) SetEngineService(v *GRPCClient) {
	x.xxx_hidden_EngineService = v
}

func (x *ToolEngineConfiguration) SetToolSets(v []*v1.CreateServiceToolSetRequest) {
	x.xxx_hidden_ToolSets = &v
}

func (x *ToolEngineConfiguration) HasEngineService() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_EngineService != nil
}

func (x *ToolEngineConfiguration) ClearEngineService() {
	x.xxx_hidden_EngineService = nil
}

type ToolEngineConfiguration_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Human-readable name for this tool engine (e.g. "onikisu").
	Name string
	// gRPC client configuration for the engine service.
	EngineService *GRPCClient
	// Tool set definitions to create from this engine.
	ToolSets []*v1.CreateServiceToolSetRequest
}

func (b0 ToolEngineConfiguration_builder) Build() *ToolEngineConfiguration {
	m0 := &ToolEngineConfiguration{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_EngineService = b.EngineService
	x.xxx_hidden_ToolSets = &b.ToolSets
	return m0
}

var File_sgpt_v1_configuration_proto protoreflect.FileDescriptor

const file_sgpt_v1_configuration_proto_rawDesc = "" +
	"\n" +
	"\x1bsgpt/v1/configuration.proto\x12\asgpt.v1\x1a\x1bbuf/validate/validate.proto\x1a\x19google/api/resource.proto\x1a'malonaz/ai/ai_engine/v1/ai_engine.proto\"\x98\x02\n" +
	"\rConfiguration\x126\n" +
	"\fsgpt_service\x18\x01 \x01(\v2\x13.sgpt.v1.GRPCClientR\vsgptService\x122\n" +
	"\n" +
	"ai_service\x18\x02 \x01(\v2\x13.sgpt.v1.GRPCClientR\taiService\x12&\n" +
	"\x06models\x18\x03 \x03(\v2\x0e.sgpt.v1.ModelR\x06models\x12.\n" +
	"\x04chat\x18\x04 \x01(\v2\x1a.sgpt.v1.ChatConfigurationR\x04chat\x12C\n" +
	"\ftool_engines\x18\x05 \x03(\v2 .sgpt.v1.ToolEngineConfigurationR\vtoolEngines\"n\n" +
	"\n" +
	"GRPCClient\x12!\n" +
	"\bbase_url\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\abaseUrl\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12$\n" +
	"\x0eapi_key_header\x18\x03 \x01(\tR\fapiKeyHeader\"R\n" +
	"\x05Model\x123\n" +
	"\x04name\x18\x01 \x01(\tB\x1f\xfaA\x16\n" +
	"\x14ai.malonaz.com/Model\xbaH\x03\xc8\x01\x01R\x04name\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\"\xdb\x01\n" +
	"\x11ChatConfiguration\x12>\n" +
	"\rsummary_model\x18\x01 \x01(\tB\x19\xfaA\x16\n" +
	"\x14ai.malonaz.com/ModelR\fsummaryModel\x12>\n" +
	"\rdefault_model\x18\x02 \x01(\tB\x19\xfaA\x16\n" +
	"\x14ai.malonaz.com/ModelR\fdefaultModel\x12!\n" +
	"\fdefault_role\x18\x03 \x01(\tR\vdefaultRole\x12#\n" +
	"\x05roles\x18\x04 \x03(\v2\r.sgpt.v1.RoleR\x05roles\"\x9f\x01\n" +
	"\x04Role\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12\x1e\n" +
	"\x06prompt\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x06prompt\x12/\n" +
	"\x05model\x18\x04 \x01(\tB\x19\xfaA\x16\n" +
	"\x14ai.malonaz.com/ModelR\x05model\x12\x14\n" +
	"\x05files\x18\x05 \x03(\tR\x05files\"\xcc\x01\n" +
	"\x17ToolEngineConfiguration\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\x12B\n" +
	"\x0eengine_service\x18\x02 \x01(\v2\x13.sgpt.v1.GRPCClientB\x06\xbaH\x03\xc8\x01\x01R\rengineService\x12Q\n" +
	"\ttool_sets\x18\x03 \x03(\v24.malonaz.ai.ai_engine.v1.CreateServiceToolSetRequestR\btoolSetsB*Z(github.com/malonaz/sgpt/genproto/sgpt/v1b\x06proto3"

var file_sgpt_v1_configuration_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_sgpt_v1_configuration_proto_goTypes = []any{
	(*Configuration)(nil),                  // 0: sgpt.v1.Configuration
	(*GRPCClient)(nil),                     // 1: sgpt.v1.GRPCClient
	(*Model)(nil),                          // 2: sgpt.v1.Model
	(*ChatConfiguration)(nil),              // 3: sgpt.v1.ChatConfiguration
	(*Role)(nil),                           // 4: sgpt.v1.Role
	(*ToolEngineConfiguration)(nil),        // 5: sgpt.v1.ToolEngineConfiguration
	(*v1.CreateServiceToolSetRequest)(nil), // 6: malonaz.ai.ai_engine.v1.CreateServiceToolSetRequest
}
var file_sgpt_v1_configuration_proto_depIdxs = []int32{
	1, // 0: sgpt.v1.Configuration.sgpt_service:type_name -> sgpt.v1.GRPCClient
	1, // 1: sgpt.v1.Configuration.ai_service:type_name -> sgpt.v1.GRPCClient
	2, // 2: sgpt.v1.Configuration.models:type_name -> sgpt.v1.Model
	3, // 3: sgpt.v1.Configuration.chat:type_name -> sgpt.v1.ChatConfiguration
	5, // 4: sgpt.v1.Configuration.tool_engines:type_name -> sgpt.v1.ToolEngineConfiguration
	4, // 5: sgpt.v1.ChatConfiguration.roles:type_name -> sgpt.v1.Role
	1, // 6: sgpt.v1.ToolEngineConfiguration.engine_service:type_name -> sgpt.v1.GRPCClient
	6, // 7: sgpt.v1.ToolEngineConfiguration.tool_sets:type_name -> malonaz.ai.ai_engine.v1.CreateServiceToolSetRequest
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_sgpt_v1_configuration_proto_init() }
func file_sgpt_v1_configuration_proto_init() {
	if File_sgpt_v1_configuration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sgpt_v1_configuration_proto_rawDesc), len(file_sgpt_v1_configuration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sgpt_v1_configuration_proto_goTypes,
		DependencyIndexes: file_sgpt_v1_configuration_proto_depIdxs,
		MessageInfos:      file_sgpt_v1_configuration_proto_msgTypes,
	}.Build()
	File_sgpt_v1_configuration_proto = out.File
	file_sgpt_v1_configuration_proto_goTypes = nil
	file_sgpt_v1_configuration_proto_depIdxs = nil
}
