// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: sgpt/v1/graph.proto

//go:build protoopaque

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A node of the knowledge graph: one human-scoped topic about a directory
// subtree, persisted as a `.sgpt/{title}.node.md` markdown file inside that
// directory: `@directive(...)` lines carry the structured fields, the body
// is the content. The graph is rooted wherever a `.sgpt.json` configuration
// lives.
type Node struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name         string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Instructions string                 `protobuf:"bytes,3,opt,name=instructions,proto3"`
	xxx_hidden_Summary      string                 `protobuf:"bytes,4,opt,name=summary,proto3"`
	xxx_hidden_Content      string                 `protobuf:"bytes,5,opt,name=content,proto3"`
	xxx_hidden_Labels       map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Files        []string               `protobuf:"bytes,9,rep,name=files,proto3"`
	xxx_hidden_CreateTime   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3"`
	xxx_hidden_UpdateTime   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=update_time,json=updateTime,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_sgpt_v1_graph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_graph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Node) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Node) GetInstructions() string {
	if x != nil {
		return x.xxx_hidden_Instructions
	}
	return ""
}

func (x *Node) GetSummary() string {
	if x != nil {
		return x.xxx_hidden_Summary
	}
	return ""
}

func (x *Node) GetContent() string {
	if x != nil {
		return x.xxx_hidden_Content
	}
	return ""
}

func (x *Node) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *Node) GetFiles() []string {
	if x != nil {
		return x.xxx_hidden_Files
	}
	return nil
}

func (x *Node) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreateTime
	}
	return nil
}

func (x *Node) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdateTime
	}
	return nil
}

func (x *Node) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Node) SetInstructions(v string) {
	x.xxx_hidden_Instructions = v
}

func (x *Node) SetSummary(v string) {
	x.xxx_hidden_Summary = v
}

func (x *Node) SetContent(v string) {
	x.xxx_hidden_Content = v
}

func (x *Node) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

func (x *Node) SetFiles(v []string) {
	x.xxx_hidden_Files = v
}

func (x *Node) SetCreateTime(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreateTime = v
}

func (x *Node) SetUpdateTime(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdateTime = v
}

func (x *Node) HasCreateTime() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreateTime != nil
}

func (x *Node) HasUpdateTime() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdateTime != nil
}

func (x *Node) ClearCreateTime() {
	x.xxx_hidden_CreateTime = nil
}

func (x *Node) ClearUpdateTime() {
	x.xxx_hidden_UpdateTime = nil
}

type Node_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Name of the node: "//{path/to/dir}:{title}", derived from the file
	// location. Never written in the file.
	Name string
	// Human-written prompt dictating what this node should capture
	// (`@instructions(...)`).
	Instructions string
	// A one-or-two-line summary of content (`@summary(...)`).
	Summary string
	// The full text of the node: the markdown body.
	Content string
	// Arbitrary user metadata (`@label("key", "value")`).
	Labels map[string]string
	// Files (root-relative) pulled in verbatim wherever this node is rendered
	// or read (`@file("path")`) — for knowledge that already lives in a
	// well-documented file (e.g. a proto API) and must not be duplicated into
	// content.
	Files []string
	// Creation time of this resource.
	CreateTime *timestamppb.Timestamp
	// Last update time of this resource.
	UpdateTime *timestamppb.Timestamp
}

func (b0 Node_builder) Build() *Node {
	m0 := &Node{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Instructions = b.Instructions
	x.xxx_hidden_Summary = b.Summary
	x.xxx_hidden_Content = b.Content
	x.xxx_hidden_Labels = b.Labels
	x.xxx_hidden_Files = b.Files
	x.xxx_hidden_CreateTime = b.CreateTime
	x.xxx_hidden_UpdateTime = b.UpdateTime
	return m0
}

var File_sgpt_v1_graph_proto protoreflect.FileDescriptor

const file_sgpt_v1_graph_proto_rawDesc = "" +
	"\n" +
	"\x13sgpt/v1/graph.proto\x12\asgpt.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xff\x02\n" +
	"\x04Node\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x03R\x04name\x12\"\n" +
	"\finstructions\x18\x03 \x01(\tR\finstructions\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x121\n" +
	"\x06labels\x18\x06 \x03(\v2\x19.sgpt.v1.Node.LabelsEntryR\x06labels\x12\x14\n" +
	"\x05files\x18\t \x03(\tR\x05files\x12@\n" +
	"\vcreate_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x12@\n" +
	"\vupdate_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"updateTime\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B*Z(github.com/malonaz/sgpt/genproto/sgpt/v1b\x06proto3"

var file_sgpt_v1_graph_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sgpt_v1_graph_proto_goTypes = []any{
	(*Node)(nil),                  // 0: sgpt.v1.Node
	nil,                           // 1: sgpt.v1.Node.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_sgpt_v1_graph_proto_depIdxs = []int32{
	1, // 0: sgpt.v1.Node.labels:type_name -> sgpt.v1.Node.LabelsEntry
	2, // 1: sgpt.v1.Node.create_time:type_name -> google.protobuf.Timestamp
	2, // 2: sgpt.v1.Node.update_time:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sgpt_v1_graph_proto_init() }
func file_sgpt_v1_graph_proto_init() {
	if File_sgpt_v1_graph_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sgpt_v1_graph_proto_rawDesc), len(file_sgpt_v1_graph_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sgpt_v1_graph_proto_goTypes,
		DependencyIndexes: file_sgpt_v1_graph_proto_depIdxs,
		MessageInfos:      file_sgpt_v1_graph_proto_msgTypes,
	}.Build()
	File_sgpt_v1_graph_proto = out.File
	file_sgpt_v1_graph_proto_goTypes = nil
	file_sgpt_v1_graph_proto_depIdxs = nil
}
