// Code generated by protoc-gen-api. DO NOT EDIT.
// source: sgpt/v1/labels.proto
package v1

type LabelFavorite struct {
	GetKey func() string
}

type LabelParentChat struct {
	GetKey func() string
}

type LabelSet struct {
	Favorite   LabelFavorite
	ParentChat LabelParentChat
}

var Labels = LabelSet{
	Favorite: LabelFavorite{
		GetKey: func() string {
			return "sgpt.com/favorite"
		},
	},
	ParentChat: LabelParentChat{
		GetKey: func() string {
			return "sgpt.com/parent-chat"
		},
	},
}
