// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: sgpt/v1/labels.proto

//go:build !protoopaque

package v1

import (
	_ "github.com/malonaz/core/genproto/codegen/aip/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_sgpt_v1_labels_proto protoreflect.FileDescriptor

const file_sgpt_v1_labels_proto_rawDesc = "" +
	"\n" +
	"\x14sgpt/v1/labels.proto\x12\asgpt.v1\x1a\"malonaz/codegen/aip/v1/label.protoB\xcc\x03\x92\x95\x150\n" +
	"\x11sgpt.com/favorite\x1a\x1bMarks a chat as a favorite.\x92\x95\x15Q\n" +
	"\x14sgpt.com/parent-chat\x1a9ID segment of the chat that launched this sub-agent chat.\x92\x95\x15\x92\x01\n" +
	"\x16sgpt.com/injected-file\x1axMarks a user message carrying the content of an injected file. The file path lives in the sgpt.com/file-path annotation.\x92\x95\x15~\n" +
	"\x10sgpt.com/context\x1ajMarks a message injected by sgpt as context (system prompt, injected files) rather than typed by the user.Z(github.com/malonaz/sgpt/genproto/sgpt/v1b\x06proto3"

var file_sgpt_v1_labels_proto_goTypes = []any{}
var file_sgpt_v1_labels_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sgpt_v1_labels_proto_init() }
func file_sgpt_v1_labels_proto_init() {
	if File_sgpt_v1_labels_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sgpt_v1_labels_proto_rawDesc), len(file_sgpt_v1_labels_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sgpt_v1_labels_proto_goTypes,
		DependencyIndexes: file_sgpt_v1_labels_proto_depIdxs,
	}.Build()
	File_sgpt_v1_labels_proto = out.File
	file_sgpt_v1_labels_proto_goTypes = nil
	file_sgpt_v1_labels_proto_depIdxs = nil
}
