// Code generated by protoc-gen-api. DO NOT EDIT.
// source: sgpt/v1/labels.proto
package v1

type LabelFavorite struct {
	GetKey func() string
}

type LabelParentChat struct {
	GetKey func() string
}

type LabelCategory struct {
	GetKey func() string
	Chat   string
	Title  string
	Agent  string
}

type LabelInjectedFile struct {
	GetKey func() string
}

type LabelContext struct {
	GetKey func() string
}

type LabelSet struct {
	Favorite     LabelFavorite
	ParentChat   LabelParentChat
	Category     LabelCategory
	InjectedFile LabelInjectedFile
	Context      LabelContext
}

var Labels = LabelSet{
	Favorite: LabelFavorite{
		GetKey: func() string {
			return "sgpt.com/favorite"
		},
	},
	ParentChat: LabelParentChat{
		GetKey: func() string {
			return "sgpt.com/parent-chat"
		},
	},
	Category: LabelCategory{
		GetKey: func() string {
			return "sgpt.com/category"
		},
		Chat:  "chat",
		Title: "title",
		Agent: "agent",
	},
	InjectedFile: LabelInjectedFile{
		GetKey: func() string {
			return "sgpt.com/injected-file"
		},
	},
	Context: LabelContext{
		GetKey: func() string {
			return "sgpt.com/context"
		},
	},
}
