// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: sgpt/v1/lore.proto

//go:build !protoopaque

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A lore: one piece of unstructured knowledge, persisted as a JSON file
// under a repo's `.sgpt/lores/{lore}.json`, where `{lore}` may contain `/`
// segments — the agent is free to organize lores into subdirectories.
// Committed with the repo, lore is shared from repo to repo via the
// configuration's imports. Lore files are written solely by the agent; each
// repo's label vocabulary is persisted in its `.sgpt/labels`.
type Lore struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Resource name of this lore: "lores/{lore}", derived from the file
	// location. Never written in the file.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Short human-readable title, shown alongside search matches.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// One-or-two-line description of the content, shown alongside search
	// matches.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// The unstructured content of the lore.
	Content *structpb.Value `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	// Arbitrary user metadata.
	Labels map[string]string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Creation time of this resource.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// Last update time of this resource.
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lore) Reset() {
	*x = Lore{}
	mi := &file_sgpt_v1_lore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lore) ProtoMessage() {}

func (x *Lore) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_lore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Lore) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Lore) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Lore) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Lore) GetContent() *structpb.Value {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Lore) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Lore) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Lore) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Lore) SetName(v string) {
	x.Name = v
}

func (x *Lore) SetTitle(v string) {
	x.Title = v
}

func (x *Lore) SetDescription(v string) {
	x.Description = v
}

func (x *Lore) SetContent(v *structpb.Value) {
	x.Content = v
}

func (x *Lore) SetLabels(v map[string]string) {
	x.Labels = v
}

func (x *Lore) SetCreateTime(v *timestamppb.Timestamp) {
	x.CreateTime = v
}

func (x *Lore) SetUpdateTime(v *timestamppb.Timestamp) {
	x.UpdateTime = v
}

func (x *Lore) HasContent() bool {
	if x == nil {
		return false
	}
	return x.Content != nil
}

func (x *Lore) HasCreateTime() bool {
	if x == nil {
		return false
	}
	return x.CreateTime != nil
}

func (x *Lore) HasUpdateTime() bool {
	if x == nil {
		return false
	}
	return x.UpdateTime != nil
}

func (x *Lore) ClearContent() {
	x.Content = nil
}

func (x *Lore) ClearCreateTime() {
	x.CreateTime = nil
}

func (x *Lore) ClearUpdateTime() {
	x.UpdateTime = nil
}

type Lore_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Resource name of this lore: "lores/{lore}", derived from the file
	// location. Never written in the file.
	Name string
	// Short human-readable title, shown alongside search matches.
	Title string
	// One-or-two-line description of the content, shown alongside search
	// matches.
	Description string
	// The unstructured content of the lore.
	Content *structpb.Value
	// Arbitrary user metadata.
	Labels map[string]string
	// Creation time of this resource.
	CreateTime *timestamppb.Timestamp
	// Last update time of this resource.
	UpdateTime *timestamppb.Timestamp
}

func (b0 Lore_builder) Build() *Lore {
	m0 := &Lore{}
	b, x := &b0, m0
	_, _ = b, x
	x.Name = b.Name
	x.Title = b.Title
	x.Description = b.Description
	x.Content = b.Content
	x.Labels = b.Labels
	x.CreateTime = b.CreateTime
	x.UpdateTime = b.UpdateTime
	return m0
}

var File_sgpt_v1_lore_proto protoreflect.FileDescriptor

const file_sgpt_v1_lore_proto_rawDesc = "" +
	"\n" +
	"\x12sgpt/v1/lore.proto\x12\asgpt.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaf\x03\n" +
	"\x04Lore\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\bR\x04name\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tB\x03\xe0A\x02R\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x120\n" +
	"\acontent\x18\x04 \x01(\v2\x16.google.protobuf.ValueR\acontent\x121\n" +
	"\x06labels\x18\x05 \x03(\v2\x19.sgpt.v1.Lore.LabelsEntryR\x06labels\x12@\n" +
	"\vcreate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"createTime\x12@\n" +
	"\vupdate_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\n" +
	"updateTime\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:-\xeaA*\n" +
	"\rsgpt.com/Lore\x12\flores/{lore}*\x05lores2\x04loreB*Z(github.com/malonaz/sgpt/genproto/sgpt/v1b\x06proto3"

var file_sgpt_v1_lore_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sgpt_v1_lore_proto_goTypes = []any{
	(*Lore)(nil),                  // 0: sgpt.v1.Lore
	nil,                           // 1: sgpt.v1.Lore.LabelsEntry
	(*structpb.Value)(nil),        // 2: google.protobuf.Value
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_sgpt_v1_lore_proto_depIdxs = []int32{
	2, // 0: sgpt.v1.Lore.content:type_name -> google.protobuf.Value
	1, // 1: sgpt.v1.Lore.labels:type_name -> sgpt.v1.Lore.LabelsEntry
	3, // 2: sgpt.v1.Lore.create_time:type_name -> google.protobuf.Timestamp
	3, // 3: sgpt.v1.Lore.update_time:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sgpt_v1_lore_proto_init() }
func file_sgpt_v1_lore_proto_init() {
	if File_sgpt_v1_lore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sgpt_v1_lore_proto_rawDesc), len(file_sgpt_v1_lore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sgpt_v1_lore_proto_goTypes,
		DependencyIndexes: file_sgpt_v1_lore_proto_depIdxs,
		MessageInfos:      file_sgpt_v1_lore_proto_msgTypes,
	}.Build()
	File_sgpt_v1_lore_proto = out.File
	file_sgpt_v1_lore_proto_goTypes = nil
	file_sgpt_v1_lore_proto_depIdxs = nil
}
