// Code generated by protoc-gen-core. DO NOT EDIT.
// source: sgpt/v1/lore.proto

package v1

import (
	fmt "fmt"
	aip "github.com/malonaz/core/go/aip"
	resourcename "go.einride.tech/aip/resourcename"
	strings "strings"
)

// LoreRnType is the resource type of LoreRn.
const LoreRnType = "sgpt.com/Lore"

// NewLoreRn is the resource named lore under parent, which must follow one of: "".
func NewLoreRn(parent string, lore string) (*LoreRn, error) {
	switch {
	case parent == "":
		n := &LoreRn{}
		n.Lore = lore
		return n, nil
	}
	return nil, fmt.Errorf("parent %q matches no parent pattern of sgpt.com/Lore", parent)
}

// LoreRnPattern is the pattern LoreRn follows.
const LoreRnPattern = "lores/{lore}"

// LoreRn is the resource name "lores/{lore}".
type LoreRn struct {
	Lore string
}

// ParseLoreRn parses and validates name against LoreRnPattern.
func ParseLoreRn(name string) (*LoreRn, error) {
	n := &LoreRn{}
	if err := n.UnmarshalString(name); err != nil {
		return nil, err
	}
	return n, nil
}

// MatchLoreRn reports whether name follows LoreRnPattern.
func MatchLoreRn(name string) bool {
	return resourcename.Match(LoreRnPattern, name)
}

func (n *LoreRn) Validate() error {
	if n.Lore == "" {
		return fmt.Errorf("lore: empty")
	}
	if strings.IndexByte(n.Lore, '/') != -1 {
		return fmt.Errorf("lore: contains illegal character '/'")
	}
	return nil
}

func (n *LoreRn) ContainsWildcard() bool {
	return n.Lore == aip.Wildcard
}

func (n *LoreRn) String() string {
	return resourcename.Sprint(LoreRnPattern, n.Lore)
}

// MarshalText implements encoding.TextMarshaler.
func (n *LoreRn) MarshalText() ([]byte, error) {
	if err := n.Validate(); err != nil {
		return nil, err
	}
	return []byte(n.String()), nil
}

// UnmarshalString parses and validates name against LoreRnPattern.
func (n *LoreRn) UnmarshalString(name string) error {
	if err := resourcename.Sscan(name, LoreRnPattern, &n.Lore); err != nil {
		return err
	}
	return n.Validate()
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (n *LoreRn) UnmarshalText(text []byte) error {
	return n.UnmarshalString(string(text))
}

func (n *LoreRn) Type() string { return LoreRnType }

func (n *LoreRn) Pattern() string { return LoreRnPattern }

func (n *LoreRn) ID() string { return n.Lore }

func (n *LoreRn) Parent() string { return "" }
