// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: sgpt/v1/tool.proto

//go:build protoopaque

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Metadata attached to a tool call via annotations.
type ToolCallMetadata struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DisplayMessage *DisplayMessage        `protobuf:"bytes,1,opt,name=display_message,json=displayMessage,proto3"`
	xxx_hidden_AutoExecute    bool                   `protobuf:"varint,2,opt,name=auto_execute,json=autoExecute,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ToolCallMetadata) Reset() {
	*x = ToolCallMetadata{}
	mi := &file_sgpt_v1_tool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallMetadata) ProtoMessage() {}

func (x *ToolCallMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_tool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ToolCallMetadata) GetDisplayMessage() *DisplayMessage {
	if x != nil {
		return x.xxx_hidden_DisplayMessage
	}
	return nil
}

func (x *ToolCallMetadata) GetAutoExecute() bool {
	if x != nil {
		return x.xxx_hidden_AutoExecute
	}
	return false
}

func (x *ToolCallMetadata) SetDisplayMessage(v *DisplayMessage) {
	x.xxx_hidden_DisplayMessage = v
}

func (x *ToolCallMetadata) SetAutoExecute(v bool) {
	x.xxx_hidden_AutoExecute = v
}

func (x *ToolCallMetadata) HasDisplayMessage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DisplayMessage != nil
}

func (x *ToolCallMetadata) ClearDisplayMessage() {
	x.xxx_hidden_DisplayMessage = nil
}

type ToolCallMetadata_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Display information for the tool call.
	DisplayMessage *DisplayMessage
	// Whether this tool call should be automatically executed without user confirmation.
	AutoExecute bool
}

func (b0 ToolCallMetadata_builder) Build() *ToolCallMetadata {
	m0 := &ToolCallMetadata{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_DisplayMessage = b.DisplayMessage
	x.xxx_hidden_AutoExecute = b.AutoExecute
	return m0
}

// Metadata attached to a tool call result via annotations.
type ToolCallResultMetadata struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DisplayMessage *DisplayMessage        `protobuf:"bytes,1,opt,name=display_message,json=displayMessage,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ToolCallResultMetadata) Reset() {
	*x = ToolCallResultMetadata{}
	mi := &file_sgpt_v1_tool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallResultMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallResultMetadata) ProtoMessage() {}

func (x *ToolCallResultMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_tool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ToolCallResultMetadata) GetDisplayMessage() *DisplayMessage {
	if x != nil {
		return x.xxx_hidden_DisplayMessage
	}
	return nil
}

func (x *ToolCallResultMetadata) SetDisplayMessage(v *DisplayMessage) {
	x.xxx_hidden_DisplayMessage = v
}

func (x *ToolCallResultMetadata) HasDisplayMessage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DisplayMessage != nil
}

func (x *ToolCallResultMetadata) ClearDisplayMessage() {
	x.xxx_hidden_DisplayMessage = nil
}

type ToolCallResultMetadata_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Display information for the tool call.
	DisplayMessage *DisplayMessage
}

func (b0 ToolCallResultMetadata_builder) Build() *ToolCallResultMetadata {
	m0 := &ToolCallResultMetadata{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_DisplayMessage = b.DisplayMessage
	return m0
}

// Information about how to display  a tool call to the user.
type DisplayMessage struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Content string                 `protobuf:"bytes,1,opt,name=content,proto3"`
	xxx_hidden_Hidden  bool                   `protobuf:"varint,2,opt,name=hidden,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DisplayMessage) Reset() {
	*x = DisplayMessage{}
	mi := &file_sgpt_v1_tool_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisplayMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplayMessage) ProtoMessage() {}

func (x *DisplayMessage) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_tool_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DisplayMessage) GetContent() string {
	if x != nil {
		return x.xxx_hidden_Content
	}
	return ""
}

func (x *DisplayMessage) GetHidden() bool {
	if x != nil {
		return x.xxx_hidden_Hidden
	}
	return false
}

func (x *DisplayMessage) SetContent(v string) {
	x.xxx_hidden_Content = v
}

func (x *DisplayMessage) SetHidden(v bool) {
	x.xxx_hidden_Hidden = v
}

type DisplayMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The message to display to the user describing what the tool call does.
	Content string
	// If set, we do not show this message.
	Hidden bool
}

func (b0 DisplayMessage_builder) Build() *DisplayMessage {
	m0 := &DisplayMessage{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Content = b.Content
	x.xxx_hidden_Hidden = b.Hidden
	return m0
}

var File_sgpt_v1_tool_proto protoreflect.FileDescriptor

const file_sgpt_v1_tool_proto_rawDesc = "" +
	"\n" +
	"\x12sgpt/v1/tool.proto\x12\asgpt.v1\"w\n" +
	"\x10ToolCallMetadata\x12@\n" +
	"\x0fdisplay_message\x18\x01 \x01(\v2\x17.sgpt.v1.DisplayMessageR\x0edisplayMessage\x12!\n" +
	"\fauto_execute\x18\x02 \x01(\bR\vautoExecute\"Z\n" +
	"\x16ToolCallResultMetadata\x12@\n" +
	"\x0fdisplay_message\x18\x01 \x01(\v2\x17.sgpt.v1.DisplayMessageR\x0edisplayMessage\"B\n" +
	"\x0eDisplayMessage\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x16\n" +
	"\x06hidden\x18\x02 \x01(\bR\x06hiddenB*Z(github.com/malonaz/sgpt/genproto/sgpt/v1b\x06proto3"

var file_sgpt_v1_tool_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sgpt_v1_tool_proto_goTypes = []any{
	(*ToolCallMetadata)(nil),       // 0: sgpt.v1.ToolCallMetadata
	(*ToolCallResultMetadata)(nil), // 1: sgpt.v1.ToolCallResultMetadata
	(*DisplayMessage)(nil),         // 2: sgpt.v1.DisplayMessage
}
var file_sgpt_v1_tool_proto_depIdxs = []int32{
	2, // 0: sgpt.v1.ToolCallMetadata.display_message:type_name -> sgpt.v1.DisplayMessage
	2, // 1: sgpt.v1.ToolCallResultMetadata.display_message:type_name -> sgpt.v1.DisplayMessage
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sgpt_v1_tool_proto_init() }
func file_sgpt_v1_tool_proto_init() {
	if File_sgpt_v1_tool_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sgpt_v1_tool_proto_rawDesc), len(file_sgpt_v1_tool_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sgpt_v1_tool_proto_goTypes,
		DependencyIndexes: file_sgpt_v1_tool_proto_depIdxs,
		MessageInfos:      file_sgpt_v1_tool_proto_msgTypes,
	}.Build()
	File_sgpt_v1_tool_proto = out.File
	file_sgpt_v1_tool_proto_goTypes = nil
	file_sgpt_v1_tool_proto_depIdxs = nil
}
