// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: sgpt/v1/tools.proto

//go:build !protoopaque

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for the `diff` tool.
type DiffRequest struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Path of the file to edit.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Unified diff to apply ('@@' line numbers are ignored).
	Diff          string `protobuf:"bytes,2,opt,name=diff,proto3" json:"diff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffRequest) Reset() {
	*x = DiffRequest{}
	mi := &file_sgpt_v1_tools_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffRequest) ProtoMessage() {}

func (x *DiffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_tools_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DiffRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DiffRequest) GetDiff() string {
	if x != nil {
		return x.Diff
	}
	return ""
}

func (x *DiffRequest) SetPath(v string) {
	x.Path = v
}

func (x *DiffRequest) SetDiff(v string) {
	x.Diff = v
}

type DiffRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Path of the file to edit.
	Path string
	// Unified diff to apply ('@@' line numbers are ignored).
	Diff string
}

func (b0 DiffRequest_builder) Build() *DiffRequest {
	m0 := &DiffRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Path = b.Path
	x.Diff = b.Diff
	return m0
}

// Result of the `diff` tool.
type DiffResponse struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Path of the edited file.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Number of hunks applied.
	HunksApplied  int32 `protobuf:"varint,2,opt,name=hunks_applied,json=hunksApplied,proto3" json:"hunks_applied,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffResponse) Reset() {
	*x = DiffResponse{}
	mi := &file_sgpt_v1_tools_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffResponse) ProtoMessage() {}

func (x *DiffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_tools_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DiffResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DiffResponse) GetHunksApplied() int32 {
	if x != nil {
		return x.HunksApplied
	}
	return 0
}

func (x *DiffResponse) SetPath(v string) {
	x.Path = v
}

func (x *DiffResponse) SetHunksApplied(v int32) {
	x.HunksApplied = v
}

type DiffResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Path of the edited file.
	Path string
	// Number of hunks applied.
	HunksApplied int32
}

func (b0 DiffResponse_builder) Build() *DiffResponse {
	m0 := &DiffResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Path = b.Path
	x.HunksApplied = b.HunksApplied
	return m0
}

// Request for the `replace` tool.
type ReplaceRequest struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Path of the file to edit.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Patches applied sequentially, each an exact search/replace.
	Patches       []*Patch `protobuf:"bytes,2,rep,name=patches,proto3" json:"patches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceRequest) Reset() {
	*x = ReplaceRequest{}
	mi := &file_sgpt_v1_tools_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceRequest) ProtoMessage() {}

func (x *ReplaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_tools_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReplaceRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReplaceRequest) GetPatches() []*Patch {
	if x != nil {
		return x.Patches
	}
	return nil
}

func (x *ReplaceRequest) SetPath(v string) {
	x.Path = v
}

func (x *ReplaceRequest) SetPatches(v []*Patch) {
	x.Patches = v
}

type ReplaceRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Path of the file to edit.
	Path string
	// Patches applied sequentially, each an exact search/replace.
	Patches []*Patch
}

func (b0 ReplaceRequest_builder) Build() *ReplaceRequest {
	m0 := &ReplaceRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Path = b.Path
	x.Patches = b.Patches
	return m0
}

// A single exact search/replace edit.
type Patch struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Exact text to find (must match exactly once unless replace_all).
	Search string `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	// Replacement text.
	Replace string `protobuf:"bytes,2,opt,name=replace,proto3" json:"replace,omitempty"`
	// Replace every occurrence instead of requiring a unique match.
	ReplaceAll    bool `protobuf:"varint,3,opt,name=replace_all,json=replaceAll,proto3" json:"replace_all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Patch) Reset() {
	*x = Patch{}
	mi := &file_sgpt_v1_tools_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Patch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Patch) ProtoMessage() {}

func (x *Patch) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_tools_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Patch) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *Patch) GetReplace() string {
	if x != nil {
		return x.Replace
	}
	return ""
}

func (x *Patch) GetReplaceAll() bool {
	if x != nil {
		return x.ReplaceAll
	}
	return false
}

func (x *Patch) SetSearch(v string) {
	x.Search = v
}

func (x *Patch) SetReplace(v string) {
	x.Replace = v
}

func (x *Patch) SetReplaceAll(v bool) {
	x.ReplaceAll = v
}

type Patch_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Exact text to find (must match exactly once unless replace_all).
	Search string
	// Replacement text.
	Replace string
	// Replace every occurrence instead of requiring a unique match.
	ReplaceAll bool
}

func (b0 Patch_builder) Build() *Patch {
	m0 := &Patch{}
	b, x := &b0, m0
	_, _ = b, x
	x.Search = b.Search
	x.Replace = b.Replace
	x.ReplaceAll = b.ReplaceAll
	return m0
}

// Result of the `replace` tool.
type ReplaceResponse struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Path of the edited file.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Number of patches applied.
	PatchesApplied int32 `protobuf:"varint,2,opt,name=patches_applied,json=patchesApplied,proto3" json:"patches_applied,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReplaceResponse) Reset() {
	*x = ReplaceResponse{}
	mi := &file_sgpt_v1_tools_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceResponse) ProtoMessage() {}

func (x *ReplaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_tools_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReplaceResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReplaceResponse) GetPatchesApplied() int32 {
	if x != nil {
		return x.PatchesApplied
	}
	return 0
}

func (x *ReplaceResponse) SetPath(v string) {
	x.Path = v
}

func (x *ReplaceResponse) SetPatchesApplied(v int32) {
	x.PatchesApplied = v
}

type ReplaceResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Path of the edited file.
	Path string
	// Number of patches applied.
	PatchesApplied int32
}

func (b0 ReplaceResponse_builder) Build() *ReplaceResponse {
	m0 := &ReplaceResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Path = b.Path
	x.PatchesApplied = b.PatchesApplied
	return m0
}

// Request for the `read_files` tool.
type ReadFilesRequest struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// List of file paths to read.
	Paths         []string `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFilesRequest) Reset() {
	*x = ReadFilesRequest{}
	mi := &file_sgpt_v1_tools_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFilesRequest) ProtoMessage() {}

func (x *ReadFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_tools_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReadFilesRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *ReadFilesRequest) SetPaths(v []string) {
	x.Paths = v
}

type ReadFilesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// List of file paths to read.
	Paths []string
}

func (b0 ReadFilesRequest_builder) Build() *ReadFilesRequest {
	m0 := &ReadFilesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Paths = b.Paths
	return m0
}

// Result of the `read_files` tool.
type ReadFilesResponse struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// One entry per requested path, in request order.
	Files         []*ReadFilesResponse_File `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFilesResponse) Reset() {
	*x = ReadFilesResponse{}
	mi := &file_sgpt_v1_tools_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFilesResponse) ProtoMessage() {}

func (x *ReadFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_tools_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReadFilesResponse) GetFiles() []*ReadFilesResponse_File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ReadFilesResponse) SetFiles(v []*ReadFilesResponse_File) {
	x.Files = v
}

type ReadFilesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// One entry per requested path, in request order.
	Files []*ReadFilesResponse_File
}

func (b0 ReadFilesResponse_builder) Build() *ReadFilesResponse {
	m0 := &ReadFilesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Files = b.Files
	return m0
}

// Request for the `exec_shell` tool.
type ExecShellRequest struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// The shell command to execute.
	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	// Optional working directory for the command execution. If not specified,
	// uses current directory.
	WorkingDirectory string `protobuf:"bytes,2,opt,name=working_directory,json=workingDirectory,proto3" json:"working_directory,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExecShellRequest) Reset() {
	*x = ExecShellRequest{}
	mi := &file_sgpt_v1_tools_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecShellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecShellRequest) ProtoMessage() {}

func (x *ExecShellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_tools_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExecShellRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecShellRequest) GetWorkingDirectory() string {
	if x != nil {
		return x.WorkingDirectory
	}
	return ""
}

func (x *ExecShellRequest) SetCommand(v string) {
	x.Command = v
}

func (x *ExecShellRequest) SetWorkingDirectory(v string) {
	x.WorkingDirectory = v
}

type ExecShellRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The shell command to execute.
	Command string
	// Optional working directory for the command execution. If not specified,
	// uses current directory.
	WorkingDirectory string
}

func (b0 ExecShellRequest_builder) Build() *ExecShellRequest {
	m0 := &ExecShellRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Command = b.Command
	x.WorkingDirectory = b.WorkingDirectory
	return m0
}

// Result of the `exec_shell` tool.
type ExecShellResponse struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Combined stdout and stderr of the command.
	Output string `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	// Process exit code; 0 on success.
	ExitCode int32 `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Set when the command failed to start or exited non-zero.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecShellResponse) Reset() {
	*x = ExecShellResponse{}
	mi := &file_sgpt_v1_tools_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecShellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecShellResponse) ProtoMessage() {}

func (x *ExecShellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_tools_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExecShellResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ExecShellResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecShellResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecShellResponse) SetOutput(v string) {
	x.Output = v
}

func (x *ExecShellResponse) SetExitCode(v int32) {
	x.ExitCode = v
}

func (x *ExecShellResponse) SetError(v string) {
	x.Error = v
}

type ExecShellResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Combined stdout and stderr of the command.
	Output string
	// Process exit code; 0 on success.
	ExitCode int32
	// Set when the command failed to start or exited non-zero.
	Error string
}

func (b0 ExecShellResponse_builder) Build() *ExecShellResponse {
	m0 := &ExecShellResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Output = b.Output
	x.ExitCode = b.ExitCode
	x.Error = b.Error
	return m0
}

// Request for the `agent` tool.
type AgentRequest struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Task for the sub-agent, including all required context.
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Short human-readable title for the sub-agent's chat (a few words).
	Title string `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	// File paths to inject into the sub-agent's context.
	Files []string `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	// Tools to grant the sub-agent (built-in tools or configured tool engines).
	Tools []string `protobuf:"bytes,3,rep,name=tools,proto3" json:"tools,omitempty"`
	// Optional model override for the sub-agent.
	Model         string `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRequest) Reset() {
	*x = AgentRequest{}
	mi := &file_sgpt_v1_tools_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRequest) ProtoMessage() {}

func (x *AgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_tools_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AgentRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *AgentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AgentRequest) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *AgentRequest) GetTools() []string {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *AgentRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AgentRequest) SetQuery(v string) {
	x.Query = v
}

func (x *AgentRequest) SetTitle(v string) {
	x.Title = v
}

func (x *AgentRequest) SetFiles(v []string) {
	x.Files = v
}

func (x *AgentRequest) SetTools(v []string) {
	x.Tools = v
}

func (x *AgentRequest) SetModel(v string) {
	x.Model = v
}

type AgentRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Task for the sub-agent, including all required context.
	Query string
	// Short human-readable title for the sub-agent's chat (a few words).
	Title string
	// File paths to inject into the sub-agent's context.
	Files []string
	// Tools to grant the sub-agent (built-in tools or configured tool engines).
	Tools []string
	// Optional model override for the sub-agent.
	Model string
}

func (b0 AgentRequest_builder) Build() *AgentRequest {
	m0 := &AgentRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Query = b.Query
	x.Title = b.Title
	x.Files = b.Files
	x.Tools = b.Tools
	x.Model = b.Model
	return m0
}

// Result of the `agent` tool.
type AgentResponse struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// The sub-agent's final answer.
	Response      string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentResponse) Reset() {
	*x = AgentResponse{}
	mi := &file_sgpt_v1_tools_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentResponse) ProtoMessage() {}

func (x *AgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_tools_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AgentResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *AgentResponse) SetResponse(v string) {
	x.Response = v
}

type AgentResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The sub-agent's final answer.
	Response string
}

func (b0 AgentResponse_builder) Build() *AgentResponse {
	m0 := &AgentResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Response = b.Response
	return m0
}

// A single file read attempt.
type ReadFilesResponse_File struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Path of the file.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// File contents; empty if the read failed.
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// Read error, if any; other files are still returned.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFilesResponse_File) Reset() {
	*x = ReadFilesResponse_File{}
	mi := &file_sgpt_v1_tools_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFilesResponse_File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFilesResponse_File) ProtoMessage() {}

func (x *ReadFilesResponse_File) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_tools_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReadFilesResponse_File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReadFilesResponse_File) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReadFilesResponse_File) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReadFilesResponse_File) SetPath(v string) {
	x.Path = v
}

func (x *ReadFilesResponse_File) SetContent(v string) {
	x.Content = v
}

func (x *ReadFilesResponse_File) SetError(v string) {
	x.Error = v
}

type ReadFilesResponse_File_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Path of the file.
	Path string
	// File contents; empty if the read failed.
	Content string
	// Read error, if any; other files are still returned.
	Error string
}

func (b0 ReadFilesResponse_File_builder) Build() *ReadFilesResponse_File {
	m0 := &ReadFilesResponse_File{}
	b, x := &b0, m0
	_, _ = b, x
	x.Path = b.Path
	x.Content = b.Content
	x.Error = b.Error
	return m0
}

var File_sgpt_v1_tools_proto protoreflect.FileDescriptor

const file_sgpt_v1_tools_proto_rawDesc = "" +
	"\n" +
	"\x13sgpt/v1/tools.proto\x12\asgpt.v1\x1a\x1fgoogle/api/field_behavior.proto\"?\n" +
	"\vDiffRequest\x12\x17\n" +
	"\x04path\x18\x01 \x01(\tB\x03\xe0A\x02R\x04path\x12\x17\n" +
	"\x04diff\x18\x02 \x01(\tB\x03\xe0A\x02R\x04diff\"G\n" +
	"\fDiffResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12#\n" +
	"\rhunks_applied\x18\x02 \x01(\x05R\fhunksApplied\"X\n" +
	"\x0eReplaceRequest\x12\x17\n" +
	"\x04path\x18\x01 \x01(\tB\x03\xe0A\x02R\x04path\x12-\n" +
	"\apatches\x18\x02 \x03(\v2\x0e.sgpt.v1.PatchB\x03\xe0A\x02R\apatches\"d\n" +
	"\x05Patch\x12\x1b\n" +
	"\x06search\x18\x01 \x01(\tB\x03\xe0A\x02R\x06search\x12\x1d\n" +
	"\areplace\x18\x02 \x01(\tB\x03\xe0A\x02R\areplace\x12\x1f\n" +
	"\vreplace_all\x18\x03 \x01(\bR\n" +
	"replaceAll\"N\n" +
	"\x0fReplaceResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12'\n" +
	"\x0fpatches_applied\x18\x02 \x01(\x05R\x0epatchesApplied\"-\n" +
	"\x10ReadFilesRequest\x12\x19\n" +
	"\x05paths\x18\x01 \x03(\tB\x03\xe0A\x02R\x05paths\"\x96\x01\n" +
	"\x11ReadFilesResponse\x125\n" +
	"\x05files\x18\x01 \x03(\v2\x1f.sgpt.v1.ReadFilesResponse.FileR\x05files\x1aJ\n" +
	"\x04File\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"^\n" +
	"\x10ExecShellRequest\x12\x1d\n" +
	"\acommand\x18\x01 \x01(\tB\x03\xe0A\x02R\acommand\x12+\n" +
	"\x11working_directory\x18\x02 \x01(\tR\x10workingDirectory\"^\n" +
	"\x11ExecShellResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x86\x01\n" +
	"\fAgentRequest\x12\x19\n" +
	"\x05query\x18\x01 \x01(\tB\x03\xe0A\x02R\x05query\x12\x19\n" +
	"\x05title\x18\x05 \x01(\tB\x03\xe0A\x02R\x05title\x12\x14\n" +
	"\x05files\x18\x02 \x03(\tR\x05files\x12\x14\n" +
	"\x05tools\x18\x03 \x03(\tR\x05tools\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\"+\n" +
	"\rAgentResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse2\xc5\x02\n" +
	"\vToolService\x123\n" +
	"\x04Diff\x12\x14.sgpt.v1.DiffRequest\x1a\x15.sgpt.v1.DiffResponse\x12<\n" +
	"\aReplace\x12\x17.sgpt.v1.ReplaceRequest\x1a\x18.sgpt.v1.ReplaceResponse\x12G\n" +
	"\tReadFiles\x12\x19.sgpt.v1.ReadFilesRequest\x1a\x1a.sgpt.v1.ReadFilesResponse\"\x03\x90\x02\x01\x12B\n" +
	"\tExecShell\x12\x19.sgpt.v1.ExecShellRequest\x1a\x1a.sgpt.v1.ExecShellResponse\x126\n" +
	"\x05Agent\x12\x15.sgpt.v1.AgentRequest\x1a\x16.sgpt.v1.AgentResponseB*Z(github.com/malonaz/sgpt/genproto/sgpt/v1b\x06proto3"

var file_sgpt_v1_tools_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_sgpt_v1_tools_proto_goTypes = []any{
	(*DiffRequest)(nil),            // 0: sgpt.v1.DiffRequest
	(*DiffResponse)(nil),           // 1: sgpt.v1.DiffResponse
	(*ReplaceRequest)(nil),         // 2: sgpt.v1.ReplaceRequest
	(*Patch)(nil),                  // 3: sgpt.v1.Patch
	(*ReplaceResponse)(nil),        // 4: sgpt.v1.ReplaceResponse
	(*ReadFilesRequest)(nil),       // 5: sgpt.v1.ReadFilesRequest
	(*ReadFilesResponse)(nil),      // 6: sgpt.v1.ReadFilesResponse
	(*ExecShellRequest)(nil),       // 7: sgpt.v1.ExecShellRequest
	(*ExecShellResponse)(nil),      // 8: sgpt.v1.ExecShellResponse
	(*AgentRequest)(nil),           // 9: sgpt.v1.AgentRequest
	(*AgentResponse)(nil),          // 10: sgpt.v1.AgentResponse
	(*ReadFilesResponse_File)(nil), // 11: sgpt.v1.ReadFilesResponse.File
}
var file_sgpt_v1_tools_proto_depIdxs = []int32{
	3,  // 0: sgpt.v1.ReplaceRequest.patches:type_name -> sgpt.v1.Patch
	11, // 1: sgpt.v1.ReadFilesResponse.files:type_name -> sgpt.v1.ReadFilesResponse.File
	0,  // 2: sgpt.v1.ToolService.Diff:input_type -> sgpt.v1.DiffRequest
	2,  // 3: sgpt.v1.ToolService.Replace:input_type -> sgpt.v1.ReplaceRequest
	5,  // 4: sgpt.v1.ToolService.ReadFiles:input_type -> sgpt.v1.ReadFilesRequest
	7,  // 5: sgpt.v1.ToolService.ExecShell:input_type -> sgpt.v1.ExecShellRequest
	9,  // 6: sgpt.v1.ToolService.Agent:input_type -> sgpt.v1.AgentRequest
	1,  // 7: sgpt.v1.ToolService.Diff:output_type -> sgpt.v1.DiffResponse
	4,  // 8: sgpt.v1.ToolService.Replace:output_type -> sgpt.v1.ReplaceResponse
	6,  // 9: sgpt.v1.ToolService.ReadFiles:output_type -> sgpt.v1.ReadFilesResponse
	8,  // 10: sgpt.v1.ToolService.ExecShell:output_type -> sgpt.v1.ExecShellResponse
	10, // 11: sgpt.v1.ToolService.Agent:output_type -> sgpt.v1.AgentResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_sgpt_v1_tools_proto_init() }
func file_sgpt_v1_tools_proto_init() {
	if File_sgpt_v1_tools_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sgpt_v1_tools_proto_rawDesc), len(file_sgpt_v1_tools_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sgpt_v1_tools_proto_goTypes,
		DependencyIndexes: file_sgpt_v1_tools_proto_depIdxs,
		MessageInfos:      file_sgpt_v1_tools_proto_msgTypes,
	}.Build()
	File_sgpt_v1_tools_proto = out.File
	file_sgpt_v1_tools_proto_goTypes = nil
	file_sgpt_v1_tools_proto_depIdxs = nil
}
