// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: sgpt/v1/tools.proto

//go:build protoopaque

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for the `diff` tool.
type DiffRequest struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Path string                 `protobuf:"bytes,1,opt,name=path,proto3"`
	xxx_hidden_Diff string                 `protobuf:"bytes,2,opt,name=diff,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DiffRequest) Reset() {
	*x = DiffRequest{}
	mi := &file_sgpt_v1_tools_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffRequest) ProtoMessage() {}

func (x *DiffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_tools_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DiffRequest) GetPath() string {
	if x != nil {
		return x.xxx_hidden_Path
	}
	return ""
}

func (x *DiffRequest) GetDiff() string {
	if x != nil {
		return x.xxx_hidden_Diff
	}
	return ""
}

func (x *DiffRequest) SetPath(v string) {
	x.xxx_hidden_Path = v
}

func (x *DiffRequest) SetDiff(v string) {
	x.xxx_hidden_Diff = v
}

type DiffRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Path of the file to edit.
	Path string
	// Unified diff to apply ('@@' line numbers are ignored).
	Diff string
}

func (b0 DiffRequest_builder) Build() *DiffRequest {
	m0 := &DiffRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Path = b.Path
	x.xxx_hidden_Diff = b.Diff
	return m0
}

// Result of the `diff` tool.
type DiffResponse struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Path         string                 `protobuf:"bytes,1,opt,name=path,proto3"`
	xxx_hidden_HunksApplied int32                  `protobuf:"varint,2,opt,name=hunks_applied,json=hunksApplied,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *DiffResponse) Reset() {
	*x = DiffResponse{}
	mi := &file_sgpt_v1_tools_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffResponse) ProtoMessage() {}

func (x *DiffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_tools_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DiffResponse) GetPath() string {
	if x != nil {
		return x.xxx_hidden_Path
	}
	return ""
}

func (x *DiffResponse) GetHunksApplied() int32 {
	if x != nil {
		return x.xxx_hidden_HunksApplied
	}
	return 0
}

func (x *DiffResponse) SetPath(v string) {
	x.xxx_hidden_Path = v
}

func (x *DiffResponse) SetHunksApplied(v int32) {
	x.xxx_hidden_HunksApplied = v
}

type DiffResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Path of the edited file.
	Path string
	// Number of hunks applied.
	HunksApplied int32
}

func (b0 DiffResponse_builder) Build() *DiffResponse {
	m0 := &DiffResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Path = b.Path
	x.xxx_hidden_HunksApplied = b.HunksApplied
	return m0
}

// Request for the `replace` tool.
type ReplaceRequest struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Path    string                 `protobuf:"bytes,1,opt,name=path,proto3"`
	xxx_hidden_Patches *[]*Patch              `protobuf:"bytes,2,rep,name=patches,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReplaceRequest) Reset() {
	*x = ReplaceRequest{}
	mi := &file_sgpt_v1_tools_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceRequest) ProtoMessage() {}

func (x *ReplaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_tools_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReplaceRequest) GetPath() string {
	if x != nil {
		return x.xxx_hidden_Path
	}
	return ""
}

func (x *ReplaceRequest) GetPatches() []*Patch {
	if x != nil {
		if x.xxx_hidden_Patches != nil {
			return *x.xxx_hidden_Patches
		}
	}
	return nil
}

func (x *ReplaceRequest) SetPath(v string) {
	x.xxx_hidden_Path = v
}

func (x *ReplaceRequest) SetPatches(v []*Patch) {
	x.xxx_hidden_Patches = &v
}

type ReplaceRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Path of the file to edit.
	Path string
	// Patches applied sequentially, each an exact search/replace.
	Patches []*Patch
}

func (b0 ReplaceRequest_builder) Build() *ReplaceRequest {
	m0 := &ReplaceRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Path = b.Path
	x.xxx_hidden_Patches = &b.Patches
	return m0
}

// A single exact search/replace edit.
type Patch struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Search     string                 `protobuf:"bytes,1,opt,name=search,proto3"`
	xxx_hidden_Replace    string                 `protobuf:"bytes,2,opt,name=replace,proto3"`
	xxx_hidden_ReplaceAll bool                   `protobuf:"varint,3,opt,name=replace_all,json=replaceAll,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Patch) Reset() {
	*x = Patch{}
	mi := &file_sgpt_v1_tools_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Patch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Patch) ProtoMessage() {}

func (x *Patch) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_tools_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Patch) GetSearch() string {
	if x != nil {
		return x.xxx_hidden_Search
	}
	return ""
}

func (x *Patch) GetReplace() string {
	if x != nil {
		return x.xxx_hidden_Replace
	}
	return ""
}

func (x *Patch) GetReplaceAll() bool {
	if x != nil {
		return x.xxx_hidden_ReplaceAll
	}
	return false
}

func (x *Patch) SetSearch(v string) {
	x.xxx_hidden_Search = v
}

func (x *Patch) SetReplace(v string) {
	x.xxx_hidden_Replace = v
}

func (x *Patch) SetReplaceAll(v bool) {
	x.xxx_hidden_ReplaceAll = v
}

type Patch_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Exact text to find (must match exactly once unless replace_all).
	Search string
	// Replacement text.
	Replace string
	// Replace every occurrence instead of requiring a unique match.
	ReplaceAll bool
}

func (b0 Patch_builder) Build() *Patch {
	m0 := &Patch{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Search = b.Search
	x.xxx_hidden_Replace = b.Replace
	x.xxx_hidden_ReplaceAll = b.ReplaceAll
	return m0
}

// Result of the `replace` tool.
type ReplaceResponse struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Path           string                 `protobuf:"bytes,1,opt,name=path,proto3"`
	xxx_hidden_PatchesApplied int32                  `protobuf:"varint,2,opt,name=patches_applied,json=patchesApplied,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ReplaceResponse) Reset() {
	*x = ReplaceResponse{}
	mi := &file_sgpt_v1_tools_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceResponse) ProtoMessage() {}

func (x *ReplaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_tools_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReplaceResponse) GetPath() string {
	if x != nil {
		return x.xxx_hidden_Path
	}
	return ""
}

func (x *ReplaceResponse) GetPatchesApplied() int32 {
	if x != nil {
		return x.xxx_hidden_PatchesApplied
	}
	return 0
}

func (x *ReplaceResponse) SetPath(v string) {
	x.xxx_hidden_Path = v
}

func (x *ReplaceResponse) SetPatchesApplied(v int32) {
	x.xxx_hidden_PatchesApplied = v
}

type ReplaceResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Path of the edited file.
	Path string
	// Number of patches applied.
	PatchesApplied int32
}

func (b0 ReplaceResponse_builder) Build() *ReplaceResponse {
	m0 := &ReplaceResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Path = b.Path
	x.xxx_hidden_PatchesApplied = b.PatchesApplied
	return m0
}

// Request for the `read_files` tool.
type ReadFilesRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Paths []string               `protobuf:"bytes,1,rep,name=paths,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReadFilesRequest) Reset() {
	*x = ReadFilesRequest{}
	mi := &file_sgpt_v1_tools_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFilesRequest) ProtoMessage() {}

func (x *ReadFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_tools_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReadFilesRequest) GetPaths() []string {
	if x != nil {
		return x.xxx_hidden_Paths
	}
	return nil
}

func (x *ReadFilesRequest) SetPaths(v []string) {
	x.xxx_hidden_Paths = v
}

type ReadFilesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// List of file paths to read.
	Paths []string
}

func (b0 ReadFilesRequest_builder) Build() *ReadFilesRequest {
	m0 := &ReadFilesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Paths = b.Paths
	return m0
}

// Result of the `read_files` tool.
type ReadFilesResponse struct {
	state            protoimpl.MessageState     `protogen:"opaque.v1"`
	xxx_hidden_Files *[]*ReadFilesResponse_File `protobuf:"bytes,1,rep,name=files,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReadFilesResponse) Reset() {
	*x = ReadFilesResponse{}
	mi := &file_sgpt_v1_tools_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFilesResponse) ProtoMessage() {}

func (x *ReadFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_tools_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReadFilesResponse) GetFiles() []*ReadFilesResponse_File {
	if x != nil {
		if x.xxx_hidden_Files != nil {
			return *x.xxx_hidden_Files
		}
	}
	return nil
}

func (x *ReadFilesResponse) SetFiles(v []*ReadFilesResponse_File) {
	x.xxx_hidden_Files = &v
}

type ReadFilesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// One entry per requested path, in request order.
	Files []*ReadFilesResponse_File
}

func (b0 ReadFilesResponse_builder) Build() *ReadFilesResponse {
	m0 := &ReadFilesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Files = &b.Files
	return m0
}

// Request for the `search_lores` tool.
type SearchLoresRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Query string                 `protobuf:"bytes,1,opt,name=query,proto3"`
	xxx_hidden_TopN  int32                  `protobuf:"varint,2,opt,name=top_n,json=topN,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SearchLoresRequest) Reset() {
	*x = SearchLoresRequest{}
	mi := &file_sgpt_v1_tools_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchLoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchLoresRequest) ProtoMessage() {}

func (x *SearchLoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_tools_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SearchLoresRequest) GetQuery() string {
	if x != nil {
		return x.xxx_hidden_Query
	}
	return ""
}

func (x *SearchLoresRequest) GetTopN() int32 {
	if x != nil {
		return x.xxx_hidden_TopN
	}
	return 0
}

func (x *SearchLoresRequest) SetQuery(v string) {
	x.xxx_hidden_Query = v
}

func (x *SearchLoresRequest) SetTopN(v int32) {
	x.xxx_hidden_TopN = v
}

type SearchLoresRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Case-insensitive regular expression (Go/RE2 syntax), run over every
	// lore's title, description, labels and content, grep-style.
	Query string
	// Maximum number of lores to return; defaults to 10.
	TopN int32
}

func (b0 SearchLoresRequest_builder) Build() *SearchLoresRequest {
	m0 := &SearchLoresRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Query = b.Query
	x.xxx_hidden_TopN = b.TopN
	return m0
}

// Result of the `search_lores` tool.
type SearchLoresResponse struct {
	state              protoimpl.MessageState        `protogen:"opaque.v1"`
	xxx_hidden_Matches *[]*SearchLoresResponse_Match `protobuf:"bytes,1,rep,name=matches,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SearchLoresResponse) Reset() {
	*x = SearchLoresResponse{}
	mi := &file_sgpt_v1_tools_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchLoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchLoresResponse) ProtoMessage() {}

func (x *SearchLoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_tools_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SearchLoresResponse) GetMatches() []*SearchLoresResponse_Match {
	if x != nil {
		if x.xxx_hidden_Matches != nil {
			return *x.xxx_hidden_Matches
		}
	}
	return nil
}

func (x *SearchLoresResponse) SetMatches(v []*SearchLoresResponse_Match) {
	x.xxx_hidden_Matches = &v
}

type SearchLoresResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Matching lores, best first, capped at top_n.
	Matches []*SearchLoresResponse_Match
}

func (b0 SearchLoresResponse_builder) Build() *SearchLoresResponse {
	m0 := &SearchLoresResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Matches = &b.Matches
	return m0
}

// Request for the `exec_shell` tool.
type ExecShellRequest struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Command          string                 `protobuf:"bytes,1,opt,name=command,proto3"`
	xxx_hidden_WorkingDirectory string                 `protobuf:"bytes,2,opt,name=working_directory,json=workingDirectory,proto3"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ExecShellRequest) Reset() {
	*x = ExecShellRequest{}
	mi := &file_sgpt_v1_tools_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecShellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecShellRequest) ProtoMessage() {}

func (x *ExecShellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_tools_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExecShellRequest) GetCommand() string {
	if x != nil {
		return x.xxx_hidden_Command
	}
	return ""
}

func (x *ExecShellRequest) GetWorkingDirectory() string {
	if x != nil {
		return x.xxx_hidden_WorkingDirectory
	}
	return ""
}

func (x *ExecShellRequest) SetCommand(v string) {
	x.xxx_hidden_Command = v
}

func (x *ExecShellRequest) SetWorkingDirectory(v string) {
	x.xxx_hidden_WorkingDirectory = v
}

type ExecShellRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The shell command to execute.
	Command string
	// Optional working directory for the command execution. If not specified,
	// uses current directory.
	WorkingDirectory string
}

func (b0 ExecShellRequest_builder) Build() *ExecShellRequest {
	m0 := &ExecShellRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Command = b.Command
	x.xxx_hidden_WorkingDirectory = b.WorkingDirectory
	return m0
}

// Result of the `exec_shell` tool.
type ExecShellResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Output   string                 `protobuf:"bytes,1,opt,name=output,proto3"`
	xxx_hidden_ExitCode int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3"`
	xxx_hidden_Error    string                 `protobuf:"bytes,3,opt,name=error,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ExecShellResponse) Reset() {
	*x = ExecShellResponse{}
	mi := &file_sgpt_v1_tools_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecShellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecShellResponse) ProtoMessage() {}

func (x *ExecShellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_tools_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExecShellResponse) GetOutput() string {
	if x != nil {
		return x.xxx_hidden_Output
	}
	return ""
}

func (x *ExecShellResponse) GetExitCode() int32 {
	if x != nil {
		return x.xxx_hidden_ExitCode
	}
	return 0
}

func (x *ExecShellResponse) GetError() string {
	if x != nil {
		return x.xxx_hidden_Error
	}
	return ""
}

func (x *ExecShellResponse) SetOutput(v string) {
	x.xxx_hidden_Output = v
}

func (x *ExecShellResponse) SetExitCode(v int32) {
	x.xxx_hidden_ExitCode = v
}

func (x *ExecShellResponse) SetError(v string) {
	x.xxx_hidden_Error = v
}

type ExecShellResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Combined stdout and stderr of the command.
	Output string
	// Process exit code; 0 on success.
	ExitCode int32
	// Set when the command failed to start or exited non-zero.
	Error string
}

func (b0 ExecShellResponse_builder) Build() *ExecShellResponse {
	m0 := &ExecShellResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Output = b.Output
	x.xxx_hidden_ExitCode = b.ExitCode
	x.xxx_hidden_Error = b.Error
	return m0
}

// Request for the `agent` tool.
type AgentRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Context     string                 `protobuf:"bytes,1,opt,name=context,proto3"`
	xxx_hidden_Tasks       *[]*AgentTask          `protobuf:"bytes,2,rep,name=tasks,proto3"`
	xxx_hidden_Files       []string               `protobuf:"bytes,3,rep,name=files,proto3"`
	xxx_hidden_Tools       []string               `protobuf:"bytes,4,rep,name=tools,proto3"`
	xxx_hidden_Model       string                 `protobuf:"bytes,5,opt,name=model,proto3"`
	xxx_hidden_Permissions *[]*PermissionRule     `protobuf:"bytes,6,rep,name=permissions,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AgentRequest) Reset() {
	*x = AgentRequest{}
	mi := &file_sgpt_v1_tools_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRequest) ProtoMessage() {}

func (x *AgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_tools_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AgentRequest) GetContext() string {
	if x != nil {
		return x.xxx_hidden_Context
	}
	return ""
}

func (x *AgentRequest) GetTasks() []*AgentTask {
	if x != nil {
		if x.xxx_hidden_Tasks != nil {
			return *x.xxx_hidden_Tasks
		}
	}
	return nil
}

func (x *AgentRequest) GetFiles() []string {
	if x != nil {
		return x.xxx_hidden_Files
	}
	return nil
}

func (x *AgentRequest) GetTools() []string {
	if x != nil {
		return x.xxx_hidden_Tools
	}
	return nil
}

func (x *AgentRequest) GetModel() string {
	if x != nil {
		return x.xxx_hidden_Model
	}
	return ""
}

func (x *AgentRequest) GetPermissions() []*PermissionRule {
	if x != nil {
		if x.xxx_hidden_Permissions != nil {
			return *x.xxx_hidden_Permissions
		}
	}
	return nil
}

func (x *AgentRequest) SetContext(v string) {
	x.xxx_hidden_Context = v
}

func (x *AgentRequest) SetTasks(v []*AgentTask) {
	x.xxx_hidden_Tasks = &v
}

func (x *AgentRequest) SetFiles(v []string) {
	x.xxx_hidden_Files = v
}

func (x *AgentRequest) SetTools(v []string) {
	x.xxx_hidden_Tools = v
}

func (x *AgentRequest) SetModel(v string) {
	x.xxx_hidden_Model = v
}

func (x *AgentRequest) SetPermissions(v []*PermissionRule) {
	x.xxx_hidden_Permissions = &v
}

type AgentRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Briefing shared by every task, prepended to each sub-agent's system
	// prompt: background, constraints, conventions, expected output format.
	Context string
	// Tasks to run concurrently, one sub-agent each.
	Tasks []*AgentTask
	// File paths injected into every sub-agent's context.
	Files []string
	// Tools granted to every sub-agent, narrowing this chat's own tools;
	// unset inherits them all. Names outside this chat's tools are rejected.
	Tools []string
	// Model for every sub-agent (name or alias); unset inherits this chat's.
	Model string
	// Permission rules for the sub-agents, first match wins. Rules can only
	// tighten what this chat may do: "deny" a tool a task must not touch, or
	// force "review" on one it should only use with the user watching.
	Permissions []*PermissionRule
}

func (b0 AgentRequest_builder) Build() *AgentRequest {
	m0 := &AgentRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Context = b.Context
	x.xxx_hidden_Tasks = &b.Tasks
	x.xxx_hidden_Files = b.Files
	x.xxx_hidden_Tools = b.Tools
	x.xxx_hidden_Model = b.Model
	x.xxx_hidden_Permissions = &b.Permissions
	return m0
}

// One sub-agent's task.
type AgentTask struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Title string                 `protobuf:"bytes,1,opt,name=title,proto3"`
	xxx_hidden_Query string                 `protobuf:"bytes,2,opt,name=query,proto3"`
	xxx_hidden_Files []string               `protobuf:"bytes,3,rep,name=files,proto3"`
	xxx_hidden_Model string                 `protobuf:"bytes,4,opt,name=model,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AgentTask) Reset() {
	*x = AgentTask{}
	mi := &file_sgpt_v1_tools_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentTask) ProtoMessage() {}

func (x *AgentTask) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_tools_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AgentTask) GetTitle() string {
	if x != nil {
		return x.xxx_hidden_Title
	}
	return ""
}

func (x *AgentTask) GetQuery() string {
	if x != nil {
		return x.xxx_hidden_Query
	}
	return ""
}

func (x *AgentTask) GetFiles() []string {
	if x != nil {
		return x.xxx_hidden_Files
	}
	return nil
}

func (x *AgentTask) GetModel() string {
	if x != nil {
		return x.xxx_hidden_Model
	}
	return ""
}

func (x *AgentTask) SetTitle(v string) {
	x.xxx_hidden_Title = v
}

func (x *AgentTask) SetQuery(v string) {
	x.xxx_hidden_Query = v
}

func (x *AgentTask) SetFiles(v []string) {
	x.xxx_hidden_Files = v
}

func (x *AgentTask) SetModel(v string) {
	x.xxx_hidden_Model = v
}

type AgentTask_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Short human-readable title for the sub-agent's chat (a few words).
	Title string
	// The task itself; the shared `context` is already in the sub-agent's
	// system prompt, so state only what is specific to this task.
	Query string
	// File paths injected into this sub-agent's context, on top of the shared
	// ones.
	Files []string
	// Model override for this task (name or alias).
	Model string
}

func (b0 AgentTask_builder) Build() *AgentTask {
	m0 := &AgentTask{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Title = b.Title
	x.xxx_hidden_Query = b.Query
	x.xxx_hidden_Files = b.Files
	x.xxx_hidden_Model = b.Model
	return m0
}

// Result of the `agent` tool.
type AgentResponse struct {
	state              protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_Results *[]*AgentResponse_Result `protobuf:"bytes,1,rep,name=results,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AgentResponse) Reset() {
	*x = AgentResponse{}
	mi := &file_sgpt_v1_tools_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentResponse) ProtoMessage() {}

func (x *AgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_tools_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AgentResponse) GetResults() []*AgentResponse_Result {
	if x != nil {
		if x.xxx_hidden_Results != nil {
			return *x.xxx_hidden_Results
		}
	}
	return nil
}

func (x *AgentResponse) SetResults(v []*AgentResponse_Result) {
	x.xxx_hidden_Results = &v
}

type AgentResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// One result per task, in request order.
	Results []*AgentResponse_Result
}

func (b0 AgentResponse_builder) Build() *AgentResponse {
	m0 := &AgentResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Results = &b.Results
	return m0
}

// A single file read attempt.
type ReadFilesResponse_File struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Path    string                 `protobuf:"bytes,1,opt,name=path,proto3"`
	xxx_hidden_Content string                 `protobuf:"bytes,2,opt,name=content,proto3"`
	xxx_hidden_Error   string                 `protobuf:"bytes,3,opt,name=error,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReadFilesResponse_File) Reset() {
	*x = ReadFilesResponse_File{}
	mi := &file_sgpt_v1_tools_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFilesResponse_File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFilesResponse_File) ProtoMessage() {}

func (x *ReadFilesResponse_File) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_tools_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReadFilesResponse_File) GetPath() string {
	if x != nil {
		return x.xxx_hidden_Path
	}
	return ""
}

func (x *ReadFilesResponse_File) GetContent() string {
	if x != nil {
		return x.xxx_hidden_Content
	}
	return ""
}

func (x *ReadFilesResponse_File) GetError() string {
	if x != nil {
		return x.xxx_hidden_Error
	}
	return ""
}

func (x *ReadFilesResponse_File) SetPath(v string) {
	x.xxx_hidden_Path = v
}

func (x *ReadFilesResponse_File) SetContent(v string) {
	x.xxx_hidden_Content = v
}

func (x *ReadFilesResponse_File) SetError(v string) {
	x.xxx_hidden_Error = v
}

type ReadFilesResponse_File_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Path of the file.
	Path string
	// File contents; empty if the read failed.
	Content string
	// Read error, if any; other files are still returned.
	Error string
}

func (b0 ReadFilesResponse_File_builder) Build() *ReadFilesResponse_File {
	m0 := &ReadFilesResponse_File{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Path = b.Path
	x.xxx_hidden_Content = b.Content
	x.xxx_hidden_Error = b.Error
	return m0
}

// One matching lore.
type SearchLoresResponse_Match struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Title       string                 `protobuf:"bytes,2,opt,name=title,proto3"`
	xxx_hidden_Description string                 `protobuf:"bytes,3,opt,name=description,proto3"`
	xxx_hidden_Labels      map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Snippets    []string               `protobuf:"bytes,5,rep,name=snippets,proto3"`
	xxx_hidden_MatchCount  int32                  `protobuf:"varint,6,opt,name=match_count,json=matchCount,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SearchLoresResponse_Match) Reset() {
	*x = SearchLoresResponse_Match{}
	mi := &file_sgpt_v1_tools_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchLoresResponse_Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchLoresResponse_Match) ProtoMessage() {}

func (x *SearchLoresResponse_Match) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_tools_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SearchLoresResponse_Match) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *SearchLoresResponse_Match) GetTitle() string {
	if x != nil {
		return x.xxx_hidden_Title
	}
	return ""
}

func (x *SearchLoresResponse_Match) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *SearchLoresResponse_Match) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *SearchLoresResponse_Match) GetSnippets() []string {
	if x != nil {
		return x.xxx_hidden_Snippets
	}
	return nil
}

func (x *SearchLoresResponse_Match) GetMatchCount() int32 {
	if x != nil {
		return x.xxx_hidden_MatchCount
	}
	return 0
}

func (x *SearchLoresResponse_Match) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *SearchLoresResponse_Match) SetTitle(v string) {
	x.xxx_hidden_Title = v
}

func (x *SearchLoresResponse_Match) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *SearchLoresResponse_Match) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

func (x *SearchLoresResponse_Match) SetSnippets(v []string) {
	x.xxx_hidden_Snippets = v
}

func (x *SearchLoresResponse_Match) SetMatchCount(v int32) {
	x.xxx_hidden_MatchCount = v
}

type SearchLoresResponse_Match_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Resource name of the lore ("lores/{lore}").
	Name string
	// The lore's title.
	Title string
	// The lore's description.
	Description string
	// The lore's labels.
	Labels map[string]string
	// Matching content lines (grep-style snippets).
	Snippets []string
	// Total number of matching lines in the lore's content.
	MatchCount int32
}

func (b0 SearchLoresResponse_Match_builder) Build() *SearchLoresResponse_Match {
	m0 := &SearchLoresResponse_Match{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Title = b.Title
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_Labels = b.Labels
	x.xxx_hidden_Snippets = b.Snippets
	x.xxx_hidden_MatchCount = b.MatchCount
	return m0
}

// One sub-agent's outcome.
type AgentResponse_Result struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Title    string                 `protobuf:"bytes,1,opt,name=title,proto3"`
	xxx_hidden_Chat     string                 `protobuf:"bytes,2,opt,name=chat,proto3"`
	xxx_hidden_Response string                 `protobuf:"bytes,3,opt,name=response,proto3"`
	xxx_hidden_Error    string                 `protobuf:"bytes,4,opt,name=error,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AgentResponse_Result) Reset() {
	*x = AgentResponse_Result{}
	mi := &file_sgpt_v1_tools_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentResponse_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentResponse_Result) ProtoMessage() {}

func (x *AgentResponse_Result) ProtoReflect() protoreflect.Message {
	mi := &file_sgpt_v1_tools_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AgentResponse_Result) GetTitle() string {
	if x != nil {
		return x.xxx_hidden_Title
	}
	return ""
}

func (x *AgentResponse_Result) GetChat() string {
	if x != nil {
		return x.xxx_hidden_Chat
	}
	return ""
}

func (x *AgentResponse_Result) GetResponse() string {
	if x != nil {
		return x.xxx_hidden_Response
	}
	return ""
}

func (x *AgentResponse_Result) GetError() string {
	if x != nil {
		return x.xxx_hidden_Error
	}
	return ""
}

func (x *AgentResponse_Result) SetTitle(v string) {
	x.xxx_hidden_Title = v
}

func (x *AgentResponse_Result) SetChat(v string) {
	x.xxx_hidden_Chat = v
}

func (x *AgentResponse_Result) SetResponse(v string) {
	x.xxx_hidden_Response = v
}

func (x *AgentResponse_Result) SetError(v string) {
	x.xxx_hidden_Error = v
}

type AgentResponse_Result_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The task's title.
	Title string
	// Resource name of the sub-agent's chat.
	Chat string
	// The sub-agent's final message; empty when it failed.
	Response string
	// Why the sub-agent produced no answer (launch rejected, turn failed,
	// cancelled); empty on success.
	Error string
}

func (b0 AgentResponse_Result_builder) Build() *AgentResponse_Result {
	m0 := &AgentResponse_Result{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Title = b.Title
	x.xxx_hidden_Chat = b.Chat
	x.xxx_hidden_Response = b.Response
	x.xxx_hidden_Error = b.Error
	return m0
}

var File_sgpt_v1_tools_proto protoreflect.FileDescriptor

const file_sgpt_v1_tools_proto_rawDesc = "" +
	"\n" +
	"\x13sgpt/v1/tools.proto\x12\asgpt.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x12sgpt/v1/tool.proto\"?\n" +
	"\vDiffRequest\x12\x17\n" +
	"\x04path\x18\x01 \x01(\tB\x03\xe0A\x02R\x04path\x12\x17\n" +
	"\x04diff\x18\x02 \x01(\tB\x03\xe0A\x02R\x04diff\"G\n" +
	"\fDiffResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12#\n" +
	"\rhunks_applied\x18\x02 \x01(\x05R\fhunksApplied\"X\n" +
	"\x0eReplaceRequest\x12\x17\n" +
	"\x04path\x18\x01 \x01(\tB\x03\xe0A\x02R\x04path\x12-\n" +
	"\apatches\x18\x02 \x03(\v2\x0e.sgpt.v1.PatchB\x03\xe0A\x02R\apatches\"d\n" +
	"\x05Patch\x12\x1b\n" +
	"\x06search\x18\x01 \x01(\tB\x03\xe0A\x02R\x06search\x12\x1d\n" +
	"\areplace\x18\x02 \x01(\tB\x03\xe0A\x02R\areplace\x12\x1f\n" +
	"\vreplace_all\x18\x03 \x01(\bR\n" +
	"replaceAll\"N\n" +
	"\x0fReplaceResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12'\n" +
	"\x0fpatches_applied\x18\x02 \x01(\x05R\x0epatchesApplied\"-\n" +
	"\x10ReadFilesRequest\x12\x19\n" +
	"\x05paths\x18\x01 \x03(\tB\x03\xe0A\x02R\x05paths\"\x96\x01\n" +
	"\x11ReadFilesResponse\x125\n" +
	"\x05files\x18\x01 \x03(\v2\x1f.sgpt.v1.ReadFilesResponse.FileR\x05files\x1aJ\n" +
	"\x04File\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"D\n" +
	"\x12SearchLoresRequest\x12\x19\n" +
	"\x05query\x18\x01 \x01(\tB\x03\xe0A\x02R\x05query\x12\x13\n" +
	"\x05top_n\x18\x02 \x01(\x05R\x04topN\"\xe9\x02\n" +
	"\x13SearchLoresResponse\x12<\n" +
	"\amatches\x18\x01 \x03(\v2\".sgpt.v1.SearchLoresResponse.MatchR\amatches\x1a\x93\x02\n" +
	"\x05Match\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12F\n" +
	"\x06labels\x18\x04 \x03(\v2..sgpt.v1.SearchLoresResponse.Match.LabelsEntryR\x06labels\x12\x1a\n" +
	"\bsnippets\x18\x05 \x03(\tR\bsnippets\x12\x1f\n" +
	"\vmatch_count\x18\x06 \x01(\x05R\n" +
	"matchCount\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"^\n" +
	"\x10ExecShellRequest\x12\x1d\n" +
	"\acommand\x18\x01 \x01(\tB\x03\xe0A\x02R\acommand\x12+\n" +
	"\x11working_directory\x18\x02 \x01(\tR\x10workingDirectory\"^\n" +
	"\x11ExecShellResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xd4\x01\n" +
	"\fAgentRequest\x12\x18\n" +
	"\acontext\x18\x01 \x01(\tR\acontext\x12-\n" +
	"\x05tasks\x18\x02 \x03(\v2\x12.sgpt.v1.AgentTaskB\x03\xe0A\x02R\x05tasks\x12\x14\n" +
	"\x05files\x18\x03 \x03(\tR\x05files\x12\x14\n" +
	"\x05tools\x18\x04 \x03(\tR\x05tools\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x129\n" +
	"\vpermissions\x18\x06 \x03(\v2\x17.sgpt.v1.PermissionRuleR\vpermissions\"m\n" +
	"\tAgentTask\x12\x19\n" +
	"\x05title\x18\x01 \x01(\tB\x03\xe0A\x02R\x05title\x12\x19\n" +
	"\x05query\x18\x02 \x01(\tB\x03\xe0A\x02R\x05query\x12\x14\n" +
	"\x05files\x18\x03 \x03(\tR\x05files\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\"\xae\x01\n" +
	"\rAgentResponse\x127\n" +
	"\aresults\x18\x01 \x03(\v2\x1d.sgpt.v1.AgentResponse.ResultR\aresults\x1ad\n" +
	"\x06Result\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04chat\x18\x02 \x01(\tR\x04chat\x12\x1a\n" +
	"\bresponse\x18\x03 \x01(\tR\bresponse\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error2\x94\x03\n" +
	"\vToolService\x123\n" +
	"\x04Diff\x12\x14.sgpt.v1.DiffRequest\x1a\x15.sgpt.v1.DiffResponse\x12<\n" +
	"\aReplace\x12\x17.sgpt.v1.ReplaceRequest\x1a\x18.sgpt.v1.ReplaceResponse\x12G\n" +
	"\tReadFiles\x12\x19.sgpt.v1.ReadFilesRequest\x1a\x1a.sgpt.v1.ReadFilesResponse\"\x03\x90\x02\x01\x12B\n" +
	"\tExecShell\x12\x19.sgpt.v1.ExecShellRequest\x1a\x1a.sgpt.v1.ExecShellResponse\x12M\n" +
	"\vSearchLores\x12\x1b.sgpt.v1.SearchLoresRequest\x1a\x1c.sgpt.v1.SearchLoresResponse\"\x03\x90\x02\x01\x126\n" +
	"\x05Agent\x12\x15.sgpt.v1.AgentRequest\x1a\x16.sgpt.v1.AgentResponseB*Z(github.com/malonaz/sgpt/genproto/sgpt/v1b\x06proto3"

var file_sgpt_v1_tools_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_sgpt_v1_tools_proto_goTypes = []any{
	(*DiffRequest)(nil),               // 0: sgpt.v1.DiffRequest
	(*DiffResponse)(nil),              // 1: sgpt.v1.DiffResponse
	(*ReplaceRequest)(nil),            // 2: sgpt.v1.ReplaceRequest
	(*Patch)(nil),                     // 3: sgpt.v1.Patch
	(*ReplaceResponse)(nil),           // 4: sgpt.v1.ReplaceResponse
	(*ReadFilesRequest)(nil),          // 5: sgpt.v1.ReadFilesRequest
	(*ReadFilesResponse)(nil),         // 6: sgpt.v1.ReadFilesResponse
	(*SearchLoresRequest)(nil),        // 7: sgpt.v1.SearchLoresRequest
	(*SearchLoresResponse)(nil),       // 8: sgpt.v1.SearchLoresResponse
	(*ExecShellRequest)(nil),          // 9: sgpt.v1.ExecShellRequest
	(*ExecShellResponse)(nil),         // 10: sgpt.v1.ExecShellResponse
	(*AgentRequest)(nil),              // 11: sgpt.v1.AgentRequest
	(*AgentTask)(nil),                 // 12: sgpt.v1.AgentTask
	(*AgentResponse)(nil),             // 13: sgpt.v1.AgentResponse
	(*ReadFilesResponse_File)(nil),    // 14: sgpt.v1.ReadFilesResponse.File
	(*SearchLoresResponse_Match)(nil), // 15: sgpt.v1.SearchLoresResponse.Match
	nil,                               // 16: sgpt.v1.SearchLoresResponse.Match.LabelsEntry
	(*AgentResponse_Result)(nil),      // 17: sgpt.v1.AgentResponse.Result
	(*PermissionRule)(nil),            // 18: sgpt.v1.PermissionRule
}
var file_sgpt_v1_tools_proto_depIdxs = []int32{
	3,  // 0: sgpt.v1.ReplaceRequest.patches:type_name -> sgpt.v1.Patch
	14, // 1: sgpt.v1.ReadFilesResponse.files:type_name -> sgpt.v1.ReadFilesResponse.File
	15, // 2: sgpt.v1.SearchLoresResponse.matches:type_name -> sgpt.v1.SearchLoresResponse.Match
	12, // 3: sgpt.v1.AgentRequest.tasks:type_name -> sgpt.v1.AgentTask
	18, // 4: sgpt.v1.AgentRequest.permissions:type_name -> sgpt.v1.PermissionRule
	17, // 5: sgpt.v1.AgentResponse.results:type_name -> sgpt.v1.AgentResponse.Result
	16, // 6: sgpt.v1.SearchLoresResponse.Match.labels:type_name -> sgpt.v1.SearchLoresResponse.Match.LabelsEntry
	0,  // 7: sgpt.v1.ToolService.Diff:input_type -> sgpt.v1.DiffRequest
	2,  // 8: sgpt.v1.ToolService.Replace:input_type -> sgpt.v1.ReplaceRequest
	5,  // 9: sgpt.v1.ToolService.ReadFiles:input_type -> sgpt.v1.ReadFilesRequest
	9,  // 10: sgpt.v1.ToolService.ExecShell:input_type -> sgpt.v1.ExecShellRequest
	7,  // 11: sgpt.v1.ToolService.SearchLores:input_type -> sgpt.v1.SearchLoresRequest
	11, // 12: sgpt.v1.ToolService.Agent:input_type -> sgpt.v1.AgentRequest
	1,  // 13: sgpt.v1.ToolService.Diff:output_type -> sgpt.v1.DiffResponse
	4,  // 14: sgpt.v1.ToolService.Replace:output_type -> sgpt.v1.ReplaceResponse
	6,  // 15: sgpt.v1.ToolService.ReadFiles:output_type -> sgpt.v1.ReadFilesResponse
	10, // 16: sgpt.v1.ToolService.ExecShell:output_type -> sgpt.v1.ExecShellResponse
	8,  // 17: sgpt.v1.ToolService.SearchLores:output_type -> sgpt.v1.SearchLoresResponse
	13, // 18: sgpt.v1.ToolService.Agent:output_type -> sgpt.v1.AgentResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_sgpt_v1_tools_proto_init() }
func file_sgpt_v1_tools_proto_init() {
	if File_sgpt_v1_tools_proto != nil {
		return
	}
	file_sgpt_v1_tool_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sgpt_v1_tools_proto_rawDesc), len(file_sgpt_v1_tools_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sgpt_v1_tools_proto_goTypes,
		DependencyIndexes: file_sgpt_v1_tools_proto_depIdxs,
		MessageInfos:      file_sgpt_v1_tools_proto_msgTypes,
	}.Build()
	File_sgpt_v1_tools_proto = out.File
	file_sgpt_v1_tools_proto_goTypes = nil
	file_sgpt_v1_tools_proto_depIdxs = nil
}
