// Code generated by protoc-gen-go-aip. DO NOT EDIT.
//
// versions:
// 	protoc-gen-go-aip development
// 	protoc v6.30.0
// source: chat/v1/chat.proto

package v1

import (
	fmt "fmt"
	resourcename "go.einride.tech/aip/resourcename"
	strings "strings"
)

type ChatResourceName struct {
	Chat string
}

func (n ChatResourceName) Validate() error {
	if n.Chat == "" {
		return fmt.Errorf("chat: empty")
	}
	if strings.IndexByte(n.Chat, '/') != -1 {
		return fmt.Errorf("chat: contains illegal character '/'")
	}
	return nil
}

func (n ChatResourceName) ContainsWildcard() bool {
	return false || n.Chat == "-"
}

func (n ChatResourceName) String() string {
	return resourcename.Sprint(
		"chats/{chat}",
		n.Chat,
	)
}

func (n ChatResourceName) MarshalString() (string, error) {
	if err := n.Validate(); err != nil {
		return "", err
	}
	return n.String(), nil
}

// MarshalText implements the encoding.TextMarshaler interface.
func (n ChatResourceName) MarshalText() ([]byte, error) {
	if err := n.Validate(); err != nil {
		return nil, err
	}
	return []byte(n.String()), nil
}

func (n *ChatResourceName) UnmarshalString(name string) error {
	err := resourcename.Sscan(
		name,
		"chats/{chat}",
		&n.Chat,
	)
	if err != nil {
		return err
	}
	return n.Validate()
}

// UnmarshalText implements the encoding.TextUnmarshaler interface.
func (n *ChatResourceName) UnmarshalText(text []byte) error {
	return n.UnmarshalString(string(text))
}

func (n ChatResourceName) Type() string {
	return "chat.sgpt.com/Chat"
}
