// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.32.1
// source: sgpt/sgpt_service/v1/chat_service.proto

package v1

import (
	context "context"
	v1 "github.com/malonaz/sgpt/genproto/sgpt/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SgptServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SgptServiceClient interface {
	// Create a chat.
	//
	// See: https://google.aip.dev/133 (Standard methods: Create).
	CreateChat(ctx context.Context, in *CreateChatRequest, opts ...grpc.CallOption) (*v1.Chat, error)
	// Update a chat.
	//
	// See: https://google.aip.dev/134 (Standard methods: Update).
	UpdateChat(ctx context.Context, in *UpdateChatRequest, opts ...grpc.CallOption) (*v1.Chat, error)
	// Delete a chat.
	//
	// See: https://google.aip.dev/135 (Standard methods: Delete).
	// See: https://google.aip.dev/164 (Soft delete).
	DeleteChat(ctx context.Context, in *DeleteChatRequest, opts ...grpc.CallOption) (*v1.Chat, error)
	// Get a chat.
	//
	// See: https://google.aip.dev/131 (Standard methods: Get).
	GetChat(ctx context.Context, in *GetChatRequest, opts ...grpc.CallOption) (*v1.Chat, error)
	// List chats.
	//
	// See: https://google.aip.dev/132 (Standard methods: List).
	ListChats(ctx context.Context, in *ListChatsRequest, opts ...grpc.CallOption) (*ListChatsResponse, error)
	// Search chats.
	//
	// See: https://google.aip.dev/136 (Custom methods).
	// See: https://google.aip.dev/158 (Pagination).
	SearchChats(ctx context.Context, in *SearchChatsRequest, opts ...grpc.CallOption) (*SearchChatsResponse, error)
}

type sgptServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSgptServiceClient(cc grpc.ClientConnInterface) SgptServiceClient {
	return &sgptServiceClient{cc}
}

func (c *sgptServiceClient) CreateChat(ctx context.Context, in *CreateChatRequest, opts ...grpc.CallOption) (*v1.Chat, error) {
	out := new(v1.Chat)
	err := c.cc.Invoke(ctx, "/sgpt.chat.chat_service.v1.ChatService/CreateChat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sgptServiceClient) UpdateChat(ctx context.Context, in *UpdateChatRequest, opts ...grpc.CallOption) (*v1.Chat, error) {
	out := new(v1.Chat)
	err := c.cc.Invoke(ctx, "/sgpt.chat.chat_service.v1.ChatService/UpdateChat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sgptServiceClient) DeleteChat(ctx context.Context, in *DeleteChatRequest, opts ...grpc.CallOption) (*v1.Chat, error) {
	out := new(v1.Chat)
	err := c.cc.Invoke(ctx, "/sgpt.chat.chat_service.v1.ChatService/DeleteChat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sgptServiceClient) GetChat(ctx context.Context, in *GetChatRequest, opts ...grpc.CallOption) (*v1.Chat, error) {
	out := new(v1.Chat)
	err := c.cc.Invoke(ctx, "/sgpt.chat.chat_service.v1.ChatService/GetChat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sgptServiceClient) ListChats(ctx context.Context, in *ListChatsRequest, opts ...grpc.CallOption) (*ListChatsResponse, error) {
	out := new(ListChatsResponse)
	err := c.cc.Invoke(ctx, "/sgpt.chat.chat_service.v1.ChatService/ListChats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sgptServiceClient) SearchChats(ctx context.Context, in *SearchChatsRequest, opts ...grpc.CallOption) (*SearchChatsResponse, error) {
	out := new(SearchChatsResponse)
	err := c.cc.Invoke(ctx, "/sgpt.chat.chat_service.v1.ChatService/SearchChats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SgptServiceServer is the server API for ChatService service.
// All implementations should embed UnimplementedSgptServiceServer
// for forward compatibility
type SgptServiceServer interface {
	// Create a chat.
	//
	// See: https://google.aip.dev/133 (Standard methods: Create).
	CreateChat(context.Context, *CreateChatRequest) (*v1.Chat, error)
	// Update a chat.
	//
	// See: https://google.aip.dev/134 (Standard methods: Update).
	UpdateChat(context.Context, *UpdateChatRequest) (*v1.Chat, error)
	// Delete a chat.
	//
	// See: https://google.aip.dev/135 (Standard methods: Delete).
	// See: https://google.aip.dev/164 (Soft delete).
	DeleteChat(context.Context, *DeleteChatRequest) (*v1.Chat, error)
	// Get a chat.
	//
	// See: https://google.aip.dev/131 (Standard methods: Get).
	GetChat(context.Context, *GetChatRequest) (*v1.Chat, error)
	// List chats.
	//
	// See: https://google.aip.dev/132 (Standard methods: List).
	ListChats(context.Context, *ListChatsRequest) (*ListChatsResponse, error)
	// Search chats.
	//
	// See: https://google.aip.dev/136 (Custom methods).
	// See: https://google.aip.dev/158 (Pagination).
	SearchChats(context.Context, *SearchChatsRequest) (*SearchChatsResponse, error)
}

// UnimplementedSgptServiceServer should be embedded to have forward compatible implementations.
type UnimplementedSgptServiceServer struct {
}

func (UnimplementedSgptServiceServer) CreateChat(context.Context, *CreateChatRequest) (*v1.Chat, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateChat not implemented")
}
func (UnimplementedSgptServiceServer) UpdateChat(context.Context, *UpdateChatRequest) (*v1.Chat, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateChat not implemented")
}
func (UnimplementedSgptServiceServer) DeleteChat(context.Context, *DeleteChatRequest) (*v1.Chat, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteChat not implemented")
}
func (UnimplementedSgptServiceServer) GetChat(context.Context, *GetChatRequest) (*v1.Chat, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChat not implemented")
}
func (UnimplementedSgptServiceServer) ListChats(context.Context, *ListChatsRequest) (*ListChatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChats not implemented")
}
func (UnimplementedSgptServiceServer) SearchChats(context.Context, *SearchChatsRequest) (*SearchChatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchChats not implemented")
}

// UnsafeSgptServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SgptServiceServer will
// result in compilation errors.
type UnsafeSgptServiceServer interface {
	mustEmbedUnimplementedSgptServiceServer()
}

func RegisterSgptServiceServer(s grpc.ServiceRegistrar, srv SgptServiceServer) {
	s.RegisterService(&ChatService_ServiceDesc, srv)
}

func _ChatService_CreateChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SgptServiceServer).CreateChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sgpt.chat.chat_service.v1.ChatService/CreateChat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SgptServiceServer).CreateChat(ctx, req.(*CreateChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_UpdateChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SgptServiceServer).UpdateChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sgpt.chat.chat_service.v1.ChatService/UpdateChat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SgptServiceServer).UpdateChat(ctx, req.(*UpdateChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_DeleteChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SgptServiceServer).DeleteChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sgpt.chat.chat_service.v1.ChatService/DeleteChat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SgptServiceServer).DeleteChat(ctx, req.(*DeleteChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SgptServiceServer).GetChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sgpt.chat.chat_service.v1.ChatService/GetChat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SgptServiceServer).GetChat(ctx, req.(*GetChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_ListChats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SgptServiceServer).ListChats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sgpt.chat.chat_service.v1.ChatService/ListChats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SgptServiceServer).ListChats(ctx, req.(*ListChatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_SearchChats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchChatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SgptServiceServer).SearchChats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sgpt.chat.chat_service.v1.ChatService/SearchChats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SgptServiceServer).SearchChats(ctx, req.(*SearchChatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatService_ServiceDesc is the grpc.ServiceDesc for ChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sgpt.chat.chat_service.v1.ChatService",
	HandlerType: (*SgptServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateChat",
			Handler:    _ChatService_CreateChat_Handler,
		},
		{
			MethodName: "UpdateChat",
			Handler:    _ChatService_UpdateChat_Handler,
		},
		{
			MethodName: "DeleteChat",
			Handler:    _ChatService_DeleteChat_Handler,
		},
		{
			MethodName: "GetChat",
			Handler:    _ChatService_GetChat_Handler,
		},
		{
			MethodName: "ListChats",
			Handler:    _ChatService_ListChats_Handler,
		},
		{
			MethodName: "SearchChats",
			Handler:    _ChatService_SearchChats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sgpt/sgpt_service/v1/chat_service.proto",
}
