// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.30.0
// source: chat/chat_service/v1/chat_service.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/malonaz/core/genproto/codegen/aip/v1"
	v1 "github.com/malonaz/sgpt/genproto/chat/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for Chat.CreateChat.
type CreateChatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the parent user for which this chat will be created.
	// Format: organizations/{organization}/users/{user}
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The ID to use for the resource, which will become the final component of
	// the resource name.
	//
	// This value should be 4-63 characters, and valid characters
	// are /[a-z][0-9]-/.
	ChatId string `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	// The chat to create.
	Chat *v1.Chat `protobuf:"bytes,3,opt,name=chat,proto3" json:"chat,omitempty"`
	// If set, validate the request and preview the review, but do not actually create the resource.
	ValidateOnly  bool `protobuf:"varint,4,opt,name=validate_only,json=validateOnly,proto3" json:"validate_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatRequest) Reset() {
	*x = CreateChatRequest{}
	mi := &file_chat_chat_service_v1_chat_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatRequest) ProtoMessage() {}

func (x *CreateChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_service_v1_chat_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatRequest.ProtoReflect.Descriptor instead.
func (*CreateChatRequest) Descriptor() ([]byte, []int) {
	return file_chat_chat_service_v1_chat_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateChatRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateChatRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *CreateChatRequest) GetChat() *v1.Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

func (x *CreateChatRequest) GetValidateOnly() bool {
	if x != nil {
		return x.ValidateOnly
	}
	return false
}

// Request message for Chat.GetChat.
type GetChatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the chat to retrieve.
	// Format: organizations/{organization}/users/{user}/chats/{chat}
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatRequest) Reset() {
	*x = GetChatRequest{}
	mi := &file_chat_chat_service_v1_chat_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatRequest) ProtoMessage() {}

func (x *GetChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_service_v1_chat_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatRequest.ProtoReflect.Descriptor instead.
func (*GetChatRequest) Descriptor() ([]byte, []int) {
	return file_chat_chat_service_v1_chat_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetChatRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request message for Chat.UpdateChat.
type UpdateChatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The chat to update with. The name must match or be empty.
	// The chat's `name` field is used to identify the chat to be updated.
	// Format: organizations/{organization}/users/{user}/chats/{chat}
	Chat *v1.Chat `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
	// The list of fields to update.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChatRequest) Reset() {
	*x = UpdateChatRequest{}
	mi := &file_chat_chat_service_v1_chat_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChatRequest) ProtoMessage() {}

func (x *UpdateChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_service_v1_chat_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChatRequest.ProtoReflect.Descriptor instead.
func (*UpdateChatRequest) Descriptor() ([]byte, []int) {
	return file_chat_chat_service_v1_chat_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateChatRequest) GetChat() *v1.Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

func (x *UpdateChatRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// Request message for Chat.DeleteChat.
type DeleteChatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the chat to delete.
	// Format: organizations/{organization}/users/{user}/chats/{chat}
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// If set to true, and the book is not found, the request will succeed
	// but no action will be taken on the server
	AllowMissing  bool `protobuf:"varint,2,opt,name=allow_missing,json=allowMissing,proto3" json:"allow_missing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatRequest) Reset() {
	*x = DeleteChatRequest{}
	mi := &file_chat_chat_service_v1_chat_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatRequest) ProtoMessage() {}

func (x *DeleteChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_service_v1_chat_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatRequest.ProtoReflect.Descriptor instead.
func (*DeleteChatRequest) Descriptor() ([]byte, []int) {
	return file_chat_chat_service_v1_chat_service_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteChatRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteChatRequest) GetAllowMissing() bool {
	if x != nil {
		return x.AllowMissing
	}
	return false
}

// Request message for Chat.ListChats.
type ListChatsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the parent, which owns this collection of chats.
	// Format: organizations/{organization}/users/{user}
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Requested page size. Server may return fewer chats than requested.
	// If unspecified, server will pick an appropriate default.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// A token identifying a page of results the server should return.
	// This is the value of
	// [ListChatsResponse.next_page_token][chat.chat_service.v1.ListChatsResponse.next_page_token]
	// returned from the previous call to `ListChats` method.
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Can order by...
	OrderBy string `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	// Can filter on id, user_id, create_time, update_time, and delete_time.
	Filter string `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`
	// If set to true, soft deleted resources will be shown.
	ShowDeleted   bool `protobuf:"varint,6,opt,name=show_deleted,json=showDeleted,proto3" json:"show_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatsRequest) Reset() {
	*x = ListChatsRequest{}
	mi := &file_chat_chat_service_v1_chat_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatsRequest) ProtoMessage() {}

func (x *ListChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_service_v1_chat_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatsRequest.ProtoReflect.Descriptor instead.
func (*ListChatsRequest) Descriptor() ([]byte, []int) {
	return file_chat_chat_service_v1_chat_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListChatsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListChatsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListChatsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListChatsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *ListChatsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListChatsRequest) GetShowDeleted() bool {
	if x != nil {
		return x.ShowDeleted
	}
	return false
}

// Response message for Chat.ListChats.
type ListChatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of chats.
	Chats []*v1.Chat `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	// A token to retrieve next page of results. Pass this value in the
	// [ListChatsRequest.page_token][chat.chat_service.v1.ListChatsRequest.page_token]
	// field in the subsequent call to `ListChats` method to retrieve the next
	// page of results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatsResponse) Reset() {
	*x = ListChatsResponse{}
	mi := &file_chat_chat_service_v1_chat_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatsResponse) ProtoMessage() {}

func (x *ListChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_service_v1_chat_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatsResponse.ProtoReflect.Descriptor instead.
func (*ListChatsResponse) Descriptor() ([]byte, []int) {
	return file_chat_chat_service_v1_chat_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListChatsResponse) GetChats() []*v1.Chat {
	if x != nil {
		return x.Chats
	}
	return nil
}

func (x *ListChatsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Request message for Chat.SearchChats.
type SearchChatsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the parent user to search chats within.
	// Format: organizations/{organization}/users/{user}
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// A filter expression.
	Filter string `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	// The search query string to match against chat content.
	//
	// This performs a full-text search across all messages in each chat's transcript.
	// The search uses PostgreSQL's `plainto_tsquery` with the 'simple' dictionary,
	// which means:
	// - Multiple words are treated as an AND query (all words must be present)
	// - Common stopwords are NOT removed (due to 'simple' configuration)
	// - No stemming is applied (searches for exact word forms)
	// - Special characters and punctuation are ignored
	//
	// Results are automatically ranked by relevance, with the most relevant
	// chats appearing first.
	//
	// Examples:
	// - "refund policy" - matches chats containing both "refund" AND "policy"
	// - "order 12345" - matches chats containing both "order" AND "12345"
	// - "how to cancel" - matches chats containing all three words
	Query string `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	// Requested page size. Server may return fewer chats than requested.
	// If unspecified, server will pick an appropriate default.
	PageSize int32 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// A token identifying a page of results the server should return.
	// This is the value of
	// [SearchChatsResponse.next_page_token][chat.chat_service.v1.SearchChatsResponse.next_page_token]
	// returned from the previous call to `SearchChats` method.
	PageToken     string `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchChatsRequest) Reset() {
	*x = SearchChatsRequest{}
	mi := &file_chat_chat_service_v1_chat_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchChatsRequest) ProtoMessage() {}

func (x *SearchChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_service_v1_chat_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchChatsRequest.ProtoReflect.Descriptor instead.
func (*SearchChatsRequest) Descriptor() ([]byte, []int) {
	return file_chat_chat_service_v1_chat_service_proto_rawDescGZIP(), []int{6}
}

func (x *SearchChatsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *SearchChatsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *SearchChatsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchChatsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchChatsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// Response message for Chat.SearchChats.
type SearchChatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of chats matching the search query.
	Chats []*v1.Chat `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	// A token to retrieve next page of results. Pass this value in the
	// [SearchChatsRequest.page_token][chat.chat_service.v1.SearchChatsRequest.page_token]
	// field in the subsequent call to `SearchChats` method to retrieve the next
	// page of results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchChatsResponse) Reset() {
	*x = SearchChatsResponse{}
	mi := &file_chat_chat_service_v1_chat_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchChatsResponse) ProtoMessage() {}

func (x *SearchChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_service_v1_chat_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchChatsResponse.ProtoReflect.Descriptor instead.
func (*SearchChatsResponse) Descriptor() ([]byte, []int) {
	return file_chat_chat_service_v1_chat_service_proto_rawDescGZIP(), []int{7}
}

func (x *SearchChatsResponse) GetChats() []*v1.Chat {
	if x != nil {
		return x.Chats
	}
	return nil
}

func (x *SearchChatsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_chat_chat_service_v1_chat_service_proto protoreflect.FileDescriptor

const file_chat_chat_service_v1_chat_service_proto_rawDesc = "" +
	"\n" +
	"'chat/chat_service/v1/chat_service.proto\x12\x19sgpt.chat.chat_service.v1\x1a\x1bbuf/validate/validate.proto\x1a\x12chat/v1/chat.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x19google/api/resource.proto\x1a google/protobuf/field_mask.proto\x1a malonaz/codegen/aip/v1/aip.proto\"\xdf\x01\n" +
	"\x11CreateChatRequest\x125\n" +
	"\x06parent\x18\x01 \x01(\tB\x1d\xfaA\x14\n" +
	"\x12user.sgpt.com/User\xbaH\x03\xc8\x01\x01R\x06parent\x12>\n" +
	"\achat_id\x18\x02 \x01(\tB%\xbaH\"\xd8\x01\x01r\x1d\x10\x01\x18?2\x17^[a-z0-9](-?[a-z0-9])*$R\x06chatId\x12.\n" +
	"\x04chat\x18\x03 \x01(\v2\x12.sgpt.chat.v1.ChatB\x06\xbaH\x03\xc8\x01\x01R\x04chat\x12#\n" +
	"\rvalidate_only\x18\x04 \x01(\bR\fvalidateOnly\"C\n" +
	"\x0eGetChatRequest\x121\n" +
	"\x04name\x18\x01 \x01(\tB\x1d\xfaA\x14\n" +
	"\x12chat.sgpt.com/Chat\xbaH\x03\xc8\x01\x01R\x04name\"\xc3\x01\n" +
	"\x11UpdateChatRequest\x12.\n" +
	"\x04chat\x18\x01 \x01(\v2\x12.sgpt.chat.v1.ChatB\x06\xbaH\x03\xc8\x01\x01R\x04chat\x12C\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"updateMask:9\xbaH1\x1a/\n" +
	"\x011\x12\x15chat.name must be set\x1a\x13has(this.chat.name)\xea\x9c\xc1\x03\x00\"k\n" +
	"\x11DeleteChatRequest\x121\n" +
	"\x04name\x18\x01 \x01(\tB\x1d\xfaA\x14\n" +
	"\x12chat.sgpt.com/Chat\xbaH\x03\xc8\x01\x01R\x04name\x12#\n" +
	"\rallow_missing\x18\x02 \x01(\bR\fallowMissing\"\xa6\x02\n" +
	"\x10ListChatsRequest\x125\n" +
	"\x06parent\x18\x01 \x01(\tB\x1d\xfaA\x14\n" +
	"\x12user.sgpt.com/User\xbaH\x03\xc8\x01\x01R\x06parent\x12'\n" +
	"\tpage_size\x18\x02 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xe8\a(\x00R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\x12\x16\n" +
	"\x06filter\x18\x05 \x01(\tR\x06filter\x12!\n" +
	"\fshow_deleted\x18\x06 \x01(\bR\vshowDeleted:=\x82\xf3-\x03\b\xc8\x01\x8a\xf3-+\n" +
	"\vcreate_time\n" +
	"\vupdate_time\x12\x0fcreate_time asc\x92\xf3-\x03\n" +
	"\x01*\"e\n" +
	"\x11ListChatsResponse\x12(\n" +
	"\x05chats\x18\x01 \x03(\v2\x12.sgpt.chat.v1.ChatR\x05chats\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xd9\x01\n" +
	"\x12SearchChatsRequest\x125\n" +
	"\x06parent\x18\x01 \x01(\tB\x1d\xfaA\x14\n" +
	"\x12user.sgpt.com/User\xbaH\x03\xc8\x01\x01R\x06parent\x12\x16\n" +
	"\x06filter\x18\x02 \x01(\tR\x06filter\x12\x1c\n" +
	"\x05query\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x05query\x12'\n" +
	"\tpage_size\x18\x04 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xe8\a(\x00R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken:\x0e\x82\xf3-\x03\b\xc8\x01\x92\xf3-\x03\n" +
	"\x01*\"g\n" +
	"\x13SearchChatsResponse\x12(\n" +
	"\x05chats\x18\x01 \x03(\v2\x12.sgpt.chat.v1.ChatR\x05chats\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\xbd\b\n" +
	"\x04Chat\x12\xae\x01\n" +
	"\n" +
	"CreateChat\x12,.sgpt.chat.chat_service.v1.CreateChatRequest\x1a\x12.sgpt.chat.v1.Chat\"^\xdaA\vparent,chat´-\x14\n" +
	"\x12chat.sgpt.com/Chat\x82\xd3\xe4\x93\x022:\x04chat\"*/v1/{parent=organizations/*/users/*}/chats\x12\xb8\x01\n" +
	"\n" +
	"UpdateChat\x12,.sgpt.chat.chat_service.v1.UpdateChatRequest\x1a\x12.sgpt.chat.v1.Chat\"h\xdaA\x10chat,update_mask´-\x14\n" +
	"\x12chat.sgpt.com/Chat\x82\xd3\xe4\x93\x027:\x04chat2//v1/{chat.name=organizations/*/users/*/chats/*}\x12\xa1\x01\n" +
	"\n" +
	"DeleteChat\x12,.sgpt.chat.chat_service.v1.DeleteChatRequest\x1a\x12.sgpt.chat.v1.Chat\"Q\xdaA\x04name´-\x14\n" +
	"\x12chat.sgpt.com/Chat\x82\xd3\xe4\x93\x02,**/v1/{name=organizations/*/users/*/chats/*}\x12\x9b\x01\n" +
	"\aGetChat\x12).sgpt.chat.chat_service.v1.GetChatRequest\x1a\x12.sgpt.chat.v1.Chat\"Q\xdaA\x04name´-\x14\n" +
	"\x12chat.sgpt.com/Chat\x82\xd3\xe4\x93\x02,\x12*/v1/{name=organizations/*/users/*/chats/*}\x12\xbb\x01\n" +
	"\tListChats\x12+.sgpt.chat.chat_service.v1.ListChatsRequest\x1a,.sgpt.chat.chat_service.v1.ListChatsResponse\"S\xdaA\x06parent´-\x14\n" +
	"\x12chat.sgpt.com/Chat\x82\xd3\xe4\x93\x02,\x12*/v1/{parent=organizations/*/users/*}/chats\x12\xb6\x01\n" +
	"\vSearchChats\x12-.sgpt.chat.chat_service.v1.SearchChatsRequest\x1a..sgpt.chat.chat_service.v1.SearchChatsResponse\"H\xdaA\fparent,query\x82\xd3\xe4\x93\x023\x121/v1/{parent=organizations/*/users/*}/chats:search\x1a\x10\xcaA\rchat.sgpt.comB7Z5github.com/malonaz/sgpt/genproto/chat/chat_service/v1b\x06proto3"

var (
	file_chat_chat_service_v1_chat_service_proto_rawDescOnce sync.Once
	file_chat_chat_service_v1_chat_service_proto_rawDescData []byte
)

func file_chat_chat_service_v1_chat_service_proto_rawDescGZIP() []byte {
	file_chat_chat_service_v1_chat_service_proto_rawDescOnce.Do(func() {
		file_chat_chat_service_v1_chat_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_chat_service_v1_chat_service_proto_rawDesc), len(file_chat_chat_service_v1_chat_service_proto_rawDesc)))
	})
	return file_chat_chat_service_v1_chat_service_proto_rawDescData
}

var file_chat_chat_service_v1_chat_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_chat_chat_service_v1_chat_service_proto_goTypes = []any{
	(*CreateChatRequest)(nil),     // 0: sgpt.chat.chat_service.v1.CreateChatRequest
	(*GetChatRequest)(nil),        // 1: sgpt.chat.chat_service.v1.GetChatRequest
	(*UpdateChatRequest)(nil),     // 2: sgpt.chat.chat_service.v1.UpdateChatRequest
	(*DeleteChatRequest)(nil),     // 3: sgpt.chat.chat_service.v1.DeleteChatRequest
	(*ListChatsRequest)(nil),      // 4: sgpt.chat.chat_service.v1.ListChatsRequest
	(*ListChatsResponse)(nil),     // 5: sgpt.chat.chat_service.v1.ListChatsResponse
	(*SearchChatsRequest)(nil),    // 6: sgpt.chat.chat_service.v1.SearchChatsRequest
	(*SearchChatsResponse)(nil),   // 7: sgpt.chat.chat_service.v1.SearchChatsResponse
	(*v1.Chat)(nil),               // 8: sgpt.chat.v1.Chat
	(*fieldmaskpb.FieldMask)(nil), // 9: google.protobuf.FieldMask
}
var file_chat_chat_service_v1_chat_service_proto_depIdxs = []int32{
	8,  // 0: sgpt.chat.chat_service.v1.CreateChatRequest.chat:type_name -> sgpt.chat.v1.Chat
	8,  // 1: sgpt.chat.chat_service.v1.UpdateChatRequest.chat:type_name -> sgpt.chat.v1.Chat
	9,  // 2: sgpt.chat.chat_service.v1.UpdateChatRequest.update_mask:type_name -> google.protobuf.FieldMask
	8,  // 3: sgpt.chat.chat_service.v1.ListChatsResponse.chats:type_name -> sgpt.chat.v1.Chat
	8,  // 4: sgpt.chat.chat_service.v1.SearchChatsResponse.chats:type_name -> sgpt.chat.v1.Chat
	0,  // 5: sgpt.chat.chat_service.v1.Chat.CreateChat:input_type -> sgpt.chat.chat_service.v1.CreateChatRequest
	2,  // 6: sgpt.chat.chat_service.v1.Chat.UpdateChat:input_type -> sgpt.chat.chat_service.v1.UpdateChatRequest
	3,  // 7: sgpt.chat.chat_service.v1.Chat.DeleteChat:input_type -> sgpt.chat.chat_service.v1.DeleteChatRequest
	1,  // 8: sgpt.chat.chat_service.v1.Chat.GetChat:input_type -> sgpt.chat.chat_service.v1.GetChatRequest
	4,  // 9: sgpt.chat.chat_service.v1.Chat.ListChats:input_type -> sgpt.chat.chat_service.v1.ListChatsRequest
	6,  // 10: sgpt.chat.chat_service.v1.Chat.SearchChats:input_type -> sgpt.chat.chat_service.v1.SearchChatsRequest
	8,  // 11: sgpt.chat.chat_service.v1.Chat.CreateChat:output_type -> sgpt.chat.v1.Chat
	8,  // 12: sgpt.chat.chat_service.v1.Chat.UpdateChat:output_type -> sgpt.chat.v1.Chat
	8,  // 13: sgpt.chat.chat_service.v1.Chat.DeleteChat:output_type -> sgpt.chat.v1.Chat
	8,  // 14: sgpt.chat.chat_service.v1.Chat.GetChat:output_type -> sgpt.chat.v1.Chat
	5,  // 15: sgpt.chat.chat_service.v1.Chat.ListChats:output_type -> sgpt.chat.chat_service.v1.ListChatsResponse
	7,  // 16: sgpt.chat.chat_service.v1.Chat.SearchChats:output_type -> sgpt.chat.chat_service.v1.SearchChatsResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_chat_chat_service_v1_chat_service_proto_init() }
func file_chat_chat_service_v1_chat_service_proto_init() {
	if File_chat_chat_service_v1_chat_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_chat_service_v1_chat_service_proto_rawDesc), len(file_chat_chat_service_v1_chat_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_chat_service_v1_chat_service_proto_goTypes,
		DependencyIndexes: file_chat_chat_service_v1_chat_service_proto_depIdxs,
		MessageInfos:      file_chat_chat_service_v1_chat_service_proto_msgTypes,
	}.Build()
	File_chat_chat_service_v1_chat_service_proto = out.File
	file_chat_chat_service_v1_chat_service_proto_goTypes = nil
	file_chat_chat_service_v1_chat_service_proto_depIdxs = nil
}
